export { buildConsentScript } from './buildConsentScript'
export { buildThemeSwitchScript } from './buildThemeSwitchScript'
export { buildCodeCopyScript } from './embed/codeCopy.embed'
export { buildModalScript } from './embed/modal.embed'
export { buildNavMenuScript } from './embed/navMenu.embed'
export { buildPagefindSearchScript } from './embed/pagefindSearch.embed'
export { buildPageTocScript } from './embed/pageToc.embed'
export { buildTabsScript } from './embed/tabs.embed'
export type { TsSsgModalApi, TsSsgTabsApi } from './runtimeGlobals'
