// This file is generated by scripts/embed.ts. Do not edit manually.
/** biome-ignore-all lint/suspicious/noTemplateCurlyInString: 'auto-generated' */

export function buildEmbeddedAuthStateHintScript() {
  return '"use strict";(()=>{var o="signed-in";if(signedInStorageKey){let e=function(){document.documentElement.classList.toggle(o,n()==="1")},n=function(){try{return localStorage.getItem(signedInStorageKey)}catch(t){return null}};g=e,r=n,e(),addEventListener("storage",t=>{t.key===signedInStorageKey&&e()})}var g,r;})();'
}
