// This file is generated by scripts/embed.ts. Do not edit manually.
/** biome-ignore-all lint/suspicious/noTemplateCurlyInString: 'auto-generated' */

export function buildMenuRuntimeScript() {
  return '"use strict";(()=>{var c="details[data-menu-runtime]";function a(e){if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",e,{once:!0});return}e()}function d(){document.addEventListener("click",l),document.addEventListener("keydown",f)}function l(e){var o;let n=e.target;if(!(n instanceof Node))return;let t=n instanceof Element?n:n.parentElement instanceof Element?n.parentElement:null,s=(o=t==null?void 0:t.closest(c))!=null?o:null;for(let u of i())u!==s&&r(u)}function f(e){if(e.key==="Escape")for(let n of i())r(n)}function i(){return Array.from(document.querySelectorAll(`${c}[open]`))}function r(e){e.removeAttribute("open")}a(d);})();'
}
