// This file is generated by scripts/embed.ts. Do not edit manually.
/** biome-ignore-all lint/suspicious/noTemplateCurlyInString: 'auto-generated' */

export function buildSignInScript() {
  return '"use strict";(()=>{var c=".sign-in";function u(e){if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",e,{once:!0});return}e()}function a(){document.addEventListener("click",d),document.addEventListener("keydown",l)}function d(e){var o;let n=e.target;if(!(n instanceof Node))return;let t=n instanceof Element?n:n.parentElement instanceof Element?n.parentElement:null,s=(o=t==null?void 0:t.closest(c))!=null?o:null;for(let i of r())i!==s&&i.removeAttribute("open")}function l(e){if(e.key==="Escape")for(let n of r())n.removeAttribute("open")}function r(){return Array.from(document.querySelectorAll(`${c}[open]`))}u(a);})();'
}
