// Generated by dts-bundle-generator v9.5.1

export declare class ComponentHead<TProps = Record<any, any>> {
	props: TProps;
	start: Comment;
	end: Comment;
	ctx: IRegorContext[];
	/** Automatically assigns properties defined in the :props binding to the component context when enabled. If disabled, props should be manually assigned using head.props.
	 * Default: true */
	autoProps: boolean;
	/** When both autoProps and entangle are enabled,
	 * the refs defined in the component context (without using head.props)
	 * become entangled with the head.props refs. (parent[ref] <==> component[ref])
	 * This means that changes to parent[ref] reflect in component[ref], and vice versa.
	 * Disable this flag to isolate refs created within the component context.
	 * Default: true */
	entangle: boolean;
	/** enables slot context switch to the parent
	 * Default: false */
	enableSwitch: boolean;
	/** A callback invoked after auto props get assigned to the component context. */
	onAutoPropsAssigned?: () => void;
	constructor(props: TProps, element: Element, ctx: IRegorContext[], start: Comment, end: Comment);
	/** use arrow syntax to be called without using head.emit.bind(head) in Binder.ts. */
	emit: (event: string, args: Record<any, any>) => void;
	unmount(): void;
}
export declare class RegorConfig {
	static getDefault(): RegorConfig;
	forGrowThreshold: number;
	globalContext: Record<string, any>;
	useInterpolation: boolean;
	constructor(globalContext?: Record<any, any>);
	addComponent<TProps = Record<any, any>>(...components: Array<Component<TProps>>): void;
	setDirectives(prefix: string): void;
	updateDirectives(updater: (directiveMap: Record<string, Directive>, builtInNames: Record<string, string>) => void): void;
}
export type IsNull<T> = [
	T
] extends [
	null
] ? true : false;
export type Equals<T, U> = T extends U ? (U extends T ? true : false) : false;
export type RawTypes = string | Function | number | boolean | symbol | undefined | null | bigint | Map<unknown, unknown> | Set<unknown> | WeakMap<object, unknown> | WeakSet<object> | Node | EventTarget | Event | RawMarker | Date | RegExp | Promise<unknown> | Error;
declare const RefSymbol: unique symbol;
declare const RawSymbol: unique symbol;
declare const ScopeSymbol: unique symbol;
export type AnyRef = (newValue?: any, eventSource?: any) => any & {
	[RefSymbol]: true;
};
export type Ref<TValueType> = ((newValue?: RefContent<TValueType> | Ref<RefParam<TValueType>> | SRef<RefContent<TValueType>>, eventSource?: any) => RefContent<TValueType>) & {
	value: RefContent<TValueType>;
};
export type SRef<TValueType> = ((newValue?: TValueType | SRef<TValueType>, eventSource?: any) => SRefContent<TValueType>) & {
	value: SRefContent<TValueType>;
};
export type ComputedRef<TValueType> = SRef<TValueType> & {
	stop: StopObserving;
};
export interface RawMarker {
	[RawSymbol]: true;
}
export type RefContent<TValueType> = TValueType extends undefined ? never : TValueType extends Ref<infer V1> ? RefContent<V1> : TValueType extends SRef<infer V2> ? V2 : TValueType extends Array<infer V3> ? Array<Ref<RefParam<V3>>> : TValueType extends RawTypes ? TValueType : {
	[Key in keyof TValueType]: Key extends symbol ? TValueType[Key] : TValueType[Key] extends Ref<infer V4> ? Ref<RefParam<V4>> : TValueType[Key] extends SRef<infer V5> ? Ref<RefParam<V5>> : TValueType[Key] extends RawMarker ? TValueType[Key] : Ref<RefParam<TValueType[Key]>>;
};
export type RefParam<TValueType> = Equals<TValueType, MakeRefParam<TValueType>> extends true ? TValueType : MakeRefParam<TValueType>;
export type MakeRefParam<TValueType> = TValueType extends undefined ? never : TValueType extends Ref<infer V1> ? MakeRefParam<V1> : TValueType extends SRef<infer V2> ? MakeRefParam<V2> : TValueType extends Array<infer V3> ? Array<MakeRefParam<V3>> : TValueType extends RawTypes ? TValueType : {
	[Key in keyof TValueType]: TValueType[Key] extends Ref<infer V4> ? MakeRefParam<V4> : TValueType[Key] extends SRef<infer V5> ? MakeRefParam<V5> : MakeRefParam<TValueType[Key]>;
};
export type SRefContent<TValueType> = Equals<TValueType, MakeSRefContent<TValueType>> extends true ? TValueType : MakeSRefContent<TValueType>;
export type MakeSRefContent<TValueType> = TValueType extends undefined ? never : TValueType extends Ref<infer V1> ? RefContent<V1> : TValueType extends SRef<infer V2> ? V2 : TValueType extends Array<infer V3> ? V3[] : TValueType extends RawTypes ? TValueType : TValueType;
export type UnwrapRef<TRef> = TRef extends Ref<infer V1> ? RefContent<V1> : TRef extends SRef<infer V2> ? SRefContent<V2> : TRef;
export type FlattenRef<TRef> = TRef extends Array<infer V1> ? Array<FlattenRef<V1>> : TRef extends Ref<infer V2> ? FlattenRef<V2> : TRef extends SRef<infer V3> ? FlattenRef<V3> : TRef extends AnyRef ? unknown : TRef extends RawTypes ? TRef : {
	[Key in keyof TRef]: FlattenRef<TRef[Key]>;
};
export type Flat<TValueType> = Equals<RefParam<TValueType>, FlattenRef<TValueType>> extends true ? RefParam<TValueType> : FlattenRef<TValueType>;
export type ObserveCallback<TValueType> = (newValue: TValueType, eventSource?: any) => void;
export type StopObserving = () => void;
export declare interface IRegorContext extends Record<any, any> {
	components?: Record<string, Component<any>>;
	mounted?: () => void;
	unmounted?: () => void;
}
export type IsLazy = (i: number, d: number) => boolean;
export type IsLazyKey = (key: string, d: number) => boolean;
export interface Directive {
	isLazy?: IsLazy;
	isLazyKey?: IsLazyKey;
	collectRefObj?: boolean;
	/** if once is enabled, the onChange is never triggered.
	 * The refs in parseResult are still reactive. */
	once?: boolean;
	/** Called on every value change. */
	onChange?: (el: HTMLElement, values: any[], previousValues?: any[], option?: any, previousOption?: any, flags?: string[]) => void;
	/** Called on binding. Returns unbinder.  */
	onBind?: (el: HTMLElement, parseResult: ParseResult, expr: string, option?: string, dynamicOption?: ParseResult, flags?: string[]) => Unbinder;
}
export interface BindData {
	unbinders: Unbinder[];
	data: Record<any, any>;
}
export type Unbinder = () => void;
export interface ParseResult {
	value: SRef<unknown[]>;
	stop: StopObserving;
	refs: Array<AnyRef | undefined>;
	context: Record<any, any>;
}
export type OnCleanup = (cleanup: () => void) => void;
export interface JSONTemplate {
	/** tag-name */
	t?: string;
	/** attributes */
	a?: Record<string, string>;
	/** children */
	c?: JSONTemplate[];
	/** text node content */
	d?: string;
	/** node type if node is COMMENT_NODE */
	n?: number;
}
/**
 * Represents a template configuration for rendering a component or an app.
 * If used with 'createApp':
 * - Define either 'selector' or 'element' to specify the mounting point.
 * - Optionally, 'html' or 'json' can be defined to override the inner HTML of the mounting point.
 * - If neither 'html' nor 'json' template is defined, the mounting point's inner HTML remains unchanged.
 * If used with 'createComponent':
 * - Define only one option: 'selector', 'element', 'html', or 'json'. The single option defines the component's HTML template.
 */
export interface Template {
	/**
	 * If used with 'createApp', specifies the target root element for mounting the application.
	 * If used with 'createComponent', identifies the component template using a selector.
	 */
	selector?: string;
	/**
	 * If used with 'createApp', represents the actual DOM element where the app will be mounted.
	 * If used with 'createComponent', specifies the component template using an element.
	 * Use this property if you already have a reference to the target element.
	 */
	element?: Node;
	/**
	 *  If used with 'createApp', HTML template string that will replace the content of the root element defined by 'selector' or 'element'.
	 * If used with 'createComponent', this template populates the content of the component.
	 */
	template?: string;
	/**
	 * JSON-based template representation, enabling rendering within secure contexts.
	 * Can be a single JSONTemplate object or an array of JSONTemplate objects.
	 * This property is applicable to both 'createApp' and 'createComponent'.
	 */
	json?: JSONTemplate | JSONTemplate[];
	/**
	 * Indicates whether the component template contains SVG elements.
	 * Enable this flag if SVG content is present to ensure proper rendering.
	 * This property is applicable to both 'createApp' and 'createComponent'.
	 */
	isSVG?: boolean;
}
export interface App<TRegorContext extends IRegorContext> {
	context: TRegorContext;
	unmount: () => void;
	unbind: () => void;
}
/**
 * Represents a component in the Regor framework.
 *
 * @typeparam TProps - The type of props accepted by the component.
 */
export interface Component<TProps = Record<any, any>> {
	/**
	 * A function that returns the Regor context associated with the component.
	 *
	 * @param head - Provides information on component mount.
	 * @returns The Regor context.
	 */
	context: (head: ComponentHead<TProps>) => IRegorContext;
	/**
	 * The template for the component.
	 */
	template: Node;
	/**
	 * Indicates whether the component's content should inherit attributes from its parent.
	 */
	inheritAttrs?: boolean;
	/**
	 * An array of prop names accepted by the component.
	 */
	props?: string[];
	/**
	 * The default name of the component when registered in the RegorConfig using the addComponent method.
	 * This property is not required if the component is used through app or component context.
	 */
	defaultName?: string;
}
export type OnMounted = () => void;
export type OnUnmounted = () => void;
export interface CreateComponentOptions<TProps = Record<any, any>> {
	useInterpolation?: boolean;
	config?: RegorConfig;
	/**
	 * A function that defines the Regor context for the component.
	 */
	context?: (head: ComponentHead<TProps>) => IRegorContext;
	inheritAttrs?: boolean;
	/**
	 * Notes on component props:
	 * The props defined in the props list can be used with :foo or r-bind:foo syntax.
	 * <MyComponent :prop-kebab-1="1" r-bind:prop-kebab-2="x ? 1 : 0" :props="{ propFoo3: true, propFoo4: x ? 'a' : 'b' }></MyComponent>
	 * It is required to define prop-kebab-1 and prop-kebab-2 in the props list camelized.
	 * It is not required to define propFoo3 and propFoo4 in the props list because it uses :props binding. :props binding enables binding to any property of component regardless it is explicitly defined in props list.
	 */
	props?: string[];
	/** The default name of the component.
	 * It is required if the component is registered using the Regor config.addComponent method.
	 * It is not required if the component being registered in app or component scope. */
	defaultName?: string;
}
export interface Scope<TRegorContext> {
	context: TRegorContext;
	unmount: () => void;
	[ScopeSymbol]: true;
}
export declare const createApp: <TRegorContext extends IRegorContext>(context: TRegorContext | Scope<TRegorContext>, template?: Template | string, config?: RegorConfig) => App<TRegorContext>;
export declare const createComponent: <TProps = Record<any, any>>(template: Template | string, options?: string[] | CreateComponentOptions<TProps>) => Component<TProps>;
export declare const toFragment: (json: JSONTemplate | JSONTemplate[], isSVG?: boolean, config?: RegorConfig) => DocumentFragment;
export declare const toJsonTemplate: (node: Element | Element[]) => JSONTemplate | JSONTemplate[];
export declare const addUnbinder: (node: Node, unbinder: Unbinder) => void;
export declare const getBindData: (node: any) => BindData;
export declare const removeNode: (node: ChildNode) => void;
export declare const unbind: (node: Node) => void;
export declare const computed: <TReturnType>(compute: () => TReturnType) => ComputedRef<UnwrapRef<TReturnType>>;
export declare const computeMany: <TReturnType>(sources: AnyRef[], compute: (...values: any[]) => TReturnType) => ComputedRef<UnwrapRef<TReturnType>>;
export declare const computeRef: <TValueType extends AnyRef, TReturnType>(source: TValueType, compute: (value: UnwrapRef<TValueType>) => TReturnType) => ComputedRef<UnwrapRef<TReturnType>>;
export declare const watchEffect: (effect: (onCleanup?: OnCleanup) => void) => StopObserving;
export declare const silence: <TReturnType>(action: () => TReturnType) => TReturnType;
export declare const collectRefs: <TReturnType>(action: () => TReturnType) => {
	value: TReturnType;
	refs: AnyRef[];
};
export declare const flatten: <TValueType>(reference: TValueType | Ref<TValueType> | SRef<TValueType> | ComputedRef<TValueType>) => Flat<TValueType>;
export declare const isRaw: (value: any) => boolean;
export type Raw<TValueType> = TValueType & RawMarker;
export declare const markRaw: <TValueType extends object>(value: TValueType) => Raw<TValueType>;
export declare const persist: <TRef extends AnyRef>(anyRef: TRef, key: string) => TRef;
export declare const html: (templates: TemplateStringsArray, ...args: any[]) => string;
export declare const raw: (templates: TemplateStringsArray, ...args: any[]) => string;
export declare const observe: <TValueType extends AnyRef>(source: TValueType, observer: ObserveCallback<UnwrapRef<TValueType>>, init?: boolean) => StopObserving;
export declare const observeMany: (sources: AnyRef[], observer: ObserveCallback<any[]>, init?: boolean) => StopObserving;
export declare const observerCount: <TValueType extends AnyRef>(source: TValueType) => number;
export declare const batch: (updater: () => void) => void;
export declare const startBatch: () => void;
export declare const endBatch: () => void;
export declare const isDeepRef: (value: unknown) => value is AnyRef;
export declare const isRef: (value: unknown) => value is AnyRef;
export declare const pause: <TValueType extends AnyRef>(source: TValueType) => void;
/**
 * Converts the given value and its nested properties into ref objects recursively and returns the ref.
 * The returned object's type reflects its nested properties as well.
 *
 * Regor provides two options to get or update the value of a ref.
 *
 * Getting the ref value:
 *
 * 1. refObj.value
 * 2. refObj()
 *
 * Setting the ref value:
 *
 * 1. refObj.value = newValue
 * 2. refObj(newValue)
 *
 * @param value - Any value to be converted into a ref object.
 * @returns A ref object representing the input value and its nested properties.
 */
export declare const ref: <TValueType>(value?: TValueType | RefContent<TValueType> | RefParam<TValueType> | (TValueType extends Ref<infer V1> ? Ref<RefParam<V1>> : never) | (TValueType extends SRef<infer V2> ? SRef<UnwrapRef<V2>> : never) | (TValueType extends (infer V1_1)[] ? V1_1[] : never) | null | undefined) => IsNull<TValueType> extends true ? Ref<unknown> : Ref<RefParam<TValueType>>;
export declare const resume: <TValueType extends AnyRef>(source: TValueType) => void;
/**
 * Converts the given value to an sref object and returns the sref.
 * A sref (short for "shallow ref") allows you to get or update its value.
 *
 * Regor provides two options to get or update the value of an sref.
 *
 * Getting the sref value:
 *
 * 1. srefObj.value
 * 2. srefObj()
 *
 * Setting the sref value:
 *
 * 1. srefObj.value = newValue
 * 2. srefObj(newValue)
 *
 * @param value - Any value to be converted into an sref object.
 * @returns An sref object representing the input value.
 */
export declare const sref: <TValueType>(value?: TValueType | (TValueType extends SRef<infer V2> ? SRef<UnwrapRef<V2>> : never) | (TValueType extends (infer V1)[] ? V1[] : never) | null | undefined) => IsNull<TValueType> extends true ? SRef<unknown> : SRef<SRefContent<TValueType>>;
export declare const trigger: <TValueType extends AnyRef>(source: TValueType, eventSource?: any, isRecursive?: boolean) => void;
export declare const unref: <TValueType>(value: TValueType) => UnwrapRef<TValueType>;
export declare const entangle: (r1: AnyRef, r2: AnyRef) => StopObserving;
export declare const useScope: <TRegorContext extends IRegorContext>(context: () => TRegorContext) => Scope<TRegorContext>;
export declare const onMounted: (onMounted: OnMounted) => void;
export declare const onUnmounted: (onUnmounted: OnUnmounted, noThrow?: boolean) => void;
export declare const warningHandler: {
	warning: {
		(...data: any[]): void;
		(message?: any, ...optionalParams: any[]): void;
	};
};

export {};
