import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

import { build } from 'esbuild'

const projectRoot = process.cwd()
const pageScriptsDir = path.join(
  projectRoot,
  'packages',
  'ts-ssg',
  'src',
  'pageScripts',
)
const embedDir = path.join(pageScriptsDir, 'embed')

const embedEntries = [
  { name: 'pageToc', fn: 'buildEmbeddedPageTocScript' },
  { name: 'navMenu', fn: 'buildEmbeddedNavMenuScript' },
  { name: 'codeCopy', fn: 'buildEmbeddedCodeCopyScript' },
  { name: 'pagefindSearch', fn: 'buildEmbeddedPagefindSearchScript' },
  { name: 'navTransitionReady', fn: 'buildEmbeddedNavTransitionReadyScript' },
  { name: 'consent', fn: 'buildEmbeddedConsentScript' },
  { name: 'themeSwitch', fn: 'buildEmbeddedThemeSwitchScript' },
] as const

function renderModule(fnName: string, script: string) {
  const serialized = JSON.stringify(script.trim())
  return [
    '// This file is generated by scripts/embed.ts. Do not edit manually.',
    "/** biome-ignore-all lint/suspicious/noTemplateCurlyInString: 'auto-generated' */",
    '',
    `export function ${fnName}() {`,
    `  return ${serialized}`,
    '}',
    '',
  ].join('\n')
}

async function main() {
  await mkdir(embedDir, { recursive: true })
  for (const entry of embedEntries) {
    const inputPath = path.join(pageScriptsDir, `${entry.name}.ts`)
    const outputPath = path.join(embedDir, `${entry.name}.embed.ts`)
    const result = await build({
      entryPoints: [inputPath],
      bundle: true,
      minify: true,
      format: 'iife',
      platform: 'browser',
      target: 'es2018',
      external: ['/pagefind/pagefind.js'],
      write: false,
    })
    const bundled = result.outputFiles?.[0]?.text
    if (!bundled) {
      throw new Error(`Failed to build embedded script for ${entry.name}.`)
    }
    await writeFile(outputPath, renderModule(entry.fn, bundled), 'utf8')
    console.log(`Embedded script generated at ${outputPath}`)
  }
}

main().catch((error) => {
  console.error('Embed failed:', error)
  process.exit(1)
})
