import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

import { build } from 'esbuild'

const projectRoot = process.cwd()
const inputPath = path.join(
  projectRoot,
  'packages',
  'ts-ssg',
  'src',
  'pageScripts',
  'pageToc.ts',
)
const outputPath = path.join(
  projectRoot,
  'packages',
  'ts-ssg',
  'src',
  'pageScripts',
  'embed',
  'pageToc.embed.ts',
)

function renderModule(script: string) {
  const serialized = JSON.stringify(script.trim())
  return [
    '// This file is generated by scripts/embed.ts. Do not edit manually.',
    '',
    'export function buildEmbeddedPageTocScript() {',
    `  return ${serialized}`,
    '}',
    '',
  ].join('\n')
}

async function main() {
  const result = await build({
    entryPoints: [inputPath],
    bundle: true,
    minify: true,
    format: 'iife',
    platform: 'browser',
    target: 'es2018',
    write: false,
  })

  const bundled = result.outputFiles?.[0]?.text
  if (!bundled) {
    throw new Error('Failed to build embedded page TOC script.')
  }

  await mkdir(path.dirname(outputPath), { recursive: true })
  await writeFile(outputPath, renderModule(bundled), 'utf8')

  console.log(`Embedded page TOC script generated at ${outputPath}`)
}

main().catch((error) => {
  console.error('Embed failed:', error)
  process.exit(1)
})
