import { spawnSync } from 'node:child_process'
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { pathToFileURL } from 'node:url'

type IconProviderName = 'iconoir' | 'lucide' | 'phosphor' | 'tabler'
const CHUNK_SIZE = 1000

interface SvgRoot {
  attributes: Record<string, string>
  innerSvg: string
}

interface GeneratedIcon {
  name: string
  svg: string
}
interface ProviderChunkMeta {
  moduleName: string
  typeName: string
  namespaceName: string
  entries: Array<{
    iconKey: string
    exportName: string
  }>
}

const projectRoot = process.cwd()
const iconsOutputDir = path.join(projectRoot, 'packages', 'ts-svg-icons', 'src')
const legacyOutputPath = path.join(
  projectRoot,
  'packages',
  'ts-svg-icons',
  'src',
  'icons.ts',
)

const lucideDefaultAttributes: Record<string, string> = {
  viewBox: '0 0 24 24',
  fill: 'none',
  stroke: 'currentColor',
  'stroke-width': '2',
  'stroke-linecap': 'round',
  'stroke-linejoin': 'round',
}

function parseSvg(svgText: string, sourcePath: string): SvgRoot {
  const cleaned = svgText.replace(/<\?xml[\s\S]*?\?>/g, '').trim()
  const match = cleaned.match(/^<svg\b([^>]*)>([\s\S]*?)<\/svg>\s*$/i)
  if (!match) {
    throw new Error(`Invalid SVG format: ${sourcePath}`)
  }
  const attributes = parseAttributes(match[1] ?? '')
  delete attributes.xmlns
  delete attributes.width
  delete attributes.height
  return {
    attributes,
    innerSvg: (match[2] ?? '').replace(/>\s+</g, '><').trim(),
  }
}

function parseAttributes(source: string): Record<string, string> {
  const attributes: Record<string, string> = {}
  const regex = /([a-zA-Z_:][-a-zA-Z0-9_:.]*)="([^"]*)"/g
  for (const match of source.matchAll(regex)) {
    const key = match[1]
    const value = match[2]
    if (!key || value === undefined) continue
    attributes[key] = value
  }
  return attributes
}

function formatAttributes(attributes: Record<string, string>): string {
  const keys = Object.keys(attributes)
  if (keys.length === 0) return ''
  return keys
    .sort()
    .map((key) => ` ${key}="${escapeAttributeValue(attributes[key] ?? '')}"`)
    .join('')
}

function escapeAttributeValue(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/"/g, '&quot;')
}

function buildSvgString(
  sourceAttributes: Record<string, string>,
  innerSvg: string,
): string {
  const attributes: Record<string, string> = {
    viewBox: sourceAttributes.viewBox ?? '0 0 24 24',
    'aria-hidden': 'true',
  }
  for (const [key, value] of Object.entries(sourceAttributes)) {
    if (key === 'viewBox') continue
    attributes[key] = value
  }
  return `<svg${formatAttributes(attributes)}>${innerSvg}</svg>`
}

function renderProviderModule(
  constName: string,
  typeName: string,
  chunkMeta: ProviderChunkMeta[],
) {
  const importLines = chunkMeta.flatMap((meta) => [
    `import type { ${meta.typeName} } from './${meta.moduleName}'`,
    `import * as ${meta.namespaceName} from './${meta.moduleName}'`,
  ])
  const unionType = chunkMeta.map((meta) => meta.typeName).join(' | ')
  const recordEntries = chunkMeta
    .flatMap((meta) =>
      meta.entries.map((entry) => {
        const value = `${meta.namespaceName}.${entry.exportName}`
        const singleLine = `  '${entry.iconKey}': ${value},`
        if (singleLine.length <= 70) return singleLine
        return `  '${entry.iconKey}':\n    ${value},`
      }),
    )
    .join('\n')

  const providerSource = [
    '// This file is generated by scripts/generate-icons.ts. Do not edit manually.',
    '',
    ...importLines,
    '',
    `export type ${typeName} = ${unionType}`,
    '',
    `export const ${constName}: Readonly<Record<${typeName}, string>> = {`,
    recordEntries,
    '}',
    '',
  ].join('\n')

  return providerSource
}

function renderProviderChunks(
  outputDir: string,
  filePrefix: string,
  typeName: string,
  provider: IconProviderName,
  icons: GeneratedIcon[],
) {
  const chunks = chunkIcons(icons, CHUNK_SIZE)
  const usedExportNames = new Set<string>()
  const chunkMeta = chunks.map((_, index) => {
    const chunkModule = `${filePrefix}.client.chunk-${index}.generated`
    return {
      index,
      chunkModule,
      chunkTypeName: `${typeName}Chunk${index}`,
      namespaceName: `${filePrefix}ClientChunk${index}`,
      chunkPath: path.join(outputDir, `${chunkModule}.ts`),
    }
  })

  const chunkFiles = chunkMeta.map((meta): { path: string; source: string } => {
    const chunkEntries = chunks[meta.index].map((icon) => {
      const exportName = toClientExportName(provider, icon.name)
      if (usedExportNames.has(exportName)) {
        throw new Error(`Duplicate client export name generated: ${exportName}`)
      }
      usedExportNames.add(exportName)
      return {
        exportName,
        iconKey: `${provider}:${icon.name}`,
        iconValue: icon.svg,
      }
    })
    const exportLines = chunkEntries
      .map((icon) => {
        return `export const ${icon.exportName} = ${JSON.stringify(icon.iconValue)}`
      })
      .join('\n')
    const typeLines = chunkEntries
      .map((icon) => `  | '${icon.iconKey}'`)
      .join('\n')
    const chunkSource = [
      '// This file is generated by scripts/generate-icons.ts. Do not edit manually.',
      '',
      exportLines,
      '',
      `export type ${meta.chunkTypeName} =`,
      typeLines,
      '',
    ].join('\n')
    return { path: meta.chunkPath, source: chunkSource }
  })

  const providerChunks: ProviderChunkMeta[] = chunkMeta.map((meta) => {
    const entries = chunks[meta.index].map((icon) => ({
      iconKey: `${provider}:${icon.name}`,
      exportName: toClientExportName(provider, icon.name),
    }))
    return {
      moduleName: meta.chunkModule,
      typeName: meta.chunkTypeName,
      namespaceName: meta.namespaceName,
      entries,
    }
  })

  const providerSource = [
    '// This file is generated by scripts/generate-icons.ts. Do not edit manually.',
    '',
    ...chunkMeta.map((meta) => `export * from './${meta.chunkModule}'`),
    '',
  ].join('\n')

  return {
    providerFile: {
      path: path.join(outputDir, `${filePrefix}.client.generated.ts`),
      source: providerSource,
    },
    chunkFiles,
    providerChunks,
  }
}

function renderGetSvgIconModule() {
  return [
    '// This file is generated by scripts/generate-icons.ts. Do not edit manually.',
    '',
    "import { ICONOIR_ICONS, type IconoirIconName } from './iconoir.generated'",
    "import { LUCIDE_ICONS, type LucideIconName } from './lucide.generated'",
    "import { PHOSPHOR_ICONS, type PhosphorIconName } from './phosphor.generated'",
    "import { TABLER_ICONS, type TablerIconName } from './tabler.generated'",
    '',
    'export type AvailableIconNames =',
    '  | IconoirIconName',
    '  | LucideIconName',
    '  | PhosphorIconName',
    '  | TablerIconName',
    '  | (string & {})',
    '',
    'const SVG_ICONS: Record<AvailableIconNames, string> = {',
    '  ...ICONOIR_ICONS,',
    '  ...LUCIDE_ICONS,',
    '  ...PHOSPHOR_ICONS,',
    '  ...TABLER_ICONS,',
    '}',
    '',
    'export function getSvgIcon(name: AvailableIconNames): string {',
    "  if (name.includes('<svg')) return name",
    '  const icon = SVG_ICONS[name]',
    `  if (!icon) throw new Error(\`Unknown icon: \${name}\`)`,
    '  return icon',
    '}',
    '',
  ].join('\n')
}

function renderIconsClientModule() {
  return [
    '// This file is generated by scripts/generate-icons.ts. Do not edit manually.',
    '',
    "export * from './iconoir.client.generated'",
    "export * from './lucide.client.generated'",
    "export * from './phosphor.client.generated'",
    "export * from './tabler.client.generated'",
    '',
  ].join('\n')
}

async function readIconoirIcons(): Promise<GeneratedIcon[]> {
  const variants = [
    { folder: 'regular', suffix: '' },
    { folder: 'solid', suffix: '-solid' },
  ] as const
  const icons: GeneratedIcon[] = []
  for (const variant of variants) {
    const iconsDir = path.join(
      projectRoot,
      'node_modules',
      'iconoir',
      'icons',
      variant.folder,
    )
    const files = await readdir(iconsDir, { withFileTypes: true })
    const svgFiles = files
      .filter((entry) => entry.isFile() && entry.name.endsWith('.svg'))
      .map((entry) => entry.name)
      .sort()
    for (const fileName of svgFiles) {
      const sourceName = fileName.replace(/\.svg$/i, '')
      const publicName = `${sourceName}${variant.suffix}`
      const svgPath = path.join(iconsDir, fileName)
      const rawSvg = await readFile(svgPath, 'utf8')
      const parsed = parseSvg(rawSvg, svgPath)
      icons.push({
        name: publicName,
        svg: buildSvgString(parsed.attributes, parsed.innerSvg),
      })
    }
  }
  return icons.sort((a, b) => a.name.localeCompare(b.name))
}

async function readLucideIcons(): Promise<GeneratedIcon[]> {
  const iconsDir = path.join(
    projectRoot,
    'node_modules',
    'lucide',
    'dist',
    'esm',
    'icons',
  )
  const files = await readdir(iconsDir, { withFileTypes: true })
  const iconModules = files
    .filter((entry) => entry.isFile() && entry.name.endsWith('.js'))
    .map((entry) => entry.name)
    .sort()
  const icons: GeneratedIcon[] = []
  for (const fileName of iconModules) {
    const sourceName = fileName.replace(/\.js$/i, '')
    const modulePath = path.join(iconsDir, fileName)
    const module = await import(pathToFileURL(modulePath).href)
    const iconNode = module.default as Array<[string, Record<string, string>]>
    const innerSvg = iconNode
      .map(([tag, attrs]) => `<${tag}${formatAttributes(attrs)}/>`)
      .join('')
    icons.push({
      name: sourceName,
      svg: buildSvgString(lucideDefaultAttributes, innerSvg),
    })
  }
  return icons
}

async function readPhosphorIcons(): Promise<GeneratedIcon[]> {
  const iconsDir = path.join(
    projectRoot,
    'node_modules',
    '@phosphor-icons',
    'core',
    'assets',
    'regular',
  )
  const files = await readdir(iconsDir, { withFileTypes: true })
  const svgFiles = files
    .filter((entry) => entry.isFile() && entry.name.endsWith('.svg'))
    .map((entry) => entry.name)
    .sort()
  const icons: GeneratedIcon[] = []
  for (const fileName of svgFiles) {
    const sourceName = fileName.replace(/\.svg$/i, '')
    const svgPath = path.join(iconsDir, fileName)
    const rawSvg = await readFile(svgPath, 'utf8')
    const parsed = parseSvg(rawSvg, svgPath)
    icons.push({
      name: sourceName,
      svg: buildSvgString(parsed.attributes, parsed.innerSvg),
    })
  }
  return icons
}

async function readTablerIcons(): Promise<GeneratedIcon[]> {
  const variants = [
    { folder: 'outline', suffix: '' },
    { folder: 'filled', suffix: '-filled' },
  ] as const
  const icons: GeneratedIcon[] = []
  for (const variant of variants) {
    const iconsDir = path.join(
      projectRoot,
      'node_modules',
      '@tabler',
      'icons',
      'icons',
      variant.folder,
    )
    const files = await readdir(iconsDir, { withFileTypes: true })
    const svgFiles = files
      .filter((entry) => entry.isFile() && entry.name.endsWith('.svg'))
      .map((entry) => entry.name)
      .sort()
    for (const fileName of svgFiles) {
      const sourceName = fileName.replace(/\.svg$/i, '')
      const publicName = `${sourceName}${variant.suffix}`
      const svgPath = path.join(iconsDir, fileName)
      const rawSvg = await readFile(svgPath, 'utf8')
      const parsed = parseSvg(rawSvg, svgPath)
      icons.push({
        name: publicName,
        svg: buildSvgString(parsed.attributes, parsed.innerSvg),
      })
    }
  }
  return icons.sort((a, b) => a.name.localeCompare(b.name))
}

async function main() {
  const [iconoirIcons, lucideIcons, phosphorIcons, tablerIcons] =
    await Promise.all([
      readIconoirIcons(),
      readLucideIcons(),
      readPhosphorIcons(),
      readTablerIcons(),
    ])
  await mkdir(iconsOutputDir, { recursive: true })

  const cleanupTargets = await readdir(iconsOutputDir, { withFileTypes: true })
  await Promise.all(
    cleanupTargets
      .filter((entry) => entry.isFile() && entry.name.endsWith('.generated.ts'))
      .map((entry) =>
        rm(path.join(iconsOutputDir, entry.name), { force: true }),
      ),
  )

  const iconoirClientOutput = renderProviderChunks(
    iconsOutputDir,
    'iconoir',
    'IconoirIconName',
    'iconoir',
    iconoirIcons,
  )
  const lucideClientOutput = renderProviderChunks(
    iconsOutputDir,
    'lucide',
    'LucideIconName',
    'lucide',
    lucideIcons,
  )
  const phosphorClientOutput = renderProviderChunks(
    iconsOutputDir,
    'phosphor',
    'PhosphorIconName',
    'phosphor',
    phosphorIcons,
  )
  const tablerClientOutput = renderProviderChunks(
    iconsOutputDir,
    'tabler',
    'TablerIconName',
    'tabler',
    tablerIcons,
  )
  const iconoirOutput = renderProviderModule(
    'ICONOIR_ICONS',
    'IconoirIconName',
    iconoirClientOutput.providerChunks,
  )
  const lucideOutput = renderProviderModule(
    'LUCIDE_ICONS',
    'LucideIconName',
    lucideClientOutput.providerChunks,
  )
  const phosphorOutput = renderProviderModule(
    'PHOSPHOR_ICONS',
    'PhosphorIconName',
    phosphorClientOutput.providerChunks,
  )
  const tablerOutput = renderProviderModule(
    'TABLER_ICONS',
    'TablerIconName',
    tablerClientOutput.providerChunks,
  )
  const getSvgIconModule = renderGetSvgIconModule()
  const clientModule = renderIconsClientModule()
  const iconoirGeneratedPath = path.join(iconsOutputDir, 'iconoir.generated.ts')
  const lucideGeneratedPath = path.join(iconsOutputDir, 'lucide.generated.ts')
  const phosphorGeneratedPath = path.join(
    iconsOutputDir,
    'phosphor.generated.ts',
  )
  const tablerGeneratedPath = path.join(iconsOutputDir, 'tabler.generated.ts')
  const getSvgIconPath = path.join(iconsOutputDir, 'getSvgIcon.ts')
  const clientPath = path.join(iconsOutputDir, 'client.ts')
  const generatedPaths = [
    iconoirGeneratedPath,
    lucideGeneratedPath,
    phosphorGeneratedPath,
    tablerGeneratedPath,
    iconoirClientOutput.providerFile.path,
    lucideClientOutput.providerFile.path,
    phosphorClientOutput.providerFile.path,
    tablerClientOutput.providerFile.path,
    ...iconoirClientOutput.chunkFiles.map((file) => file.path),
    ...lucideClientOutput.chunkFiles.map((file) => file.path),
    ...phosphorClientOutput.chunkFiles.map((file) => file.path),
    ...tablerClientOutput.chunkFiles.map((file) => file.path),
    getSvgIconPath,
    clientPath,
  ]

  await Promise.all([
    writeFile(iconoirGeneratedPath, iconoirOutput, 'utf8'),
    writeFile(lucideGeneratedPath, lucideOutput, 'utf8'),
    writeFile(phosphorGeneratedPath, phosphorOutput, 'utf8'),
    writeFile(tablerGeneratedPath, tablerOutput, 'utf8'),
    writeFile(
      iconoirClientOutput.providerFile.path,
      iconoirClientOutput.providerFile.source,
      'utf8',
    ),
    writeFile(
      lucideClientOutput.providerFile.path,
      lucideClientOutput.providerFile.source,
      'utf8',
    ),
    writeFile(
      phosphorClientOutput.providerFile.path,
      phosphorClientOutput.providerFile.source,
      'utf8',
    ),
    writeFile(
      tablerClientOutput.providerFile.path,
      tablerClientOutput.providerFile.source,
      'utf8',
    ),
    ...iconoirClientOutput.chunkFiles.map((file) =>
      writeFile(file.path, file.source, 'utf8'),
    ),
    ...lucideClientOutput.chunkFiles.map((file) =>
      writeFile(file.path, file.source, 'utf8'),
    ),
    ...phosphorClientOutput.chunkFiles.map((file) =>
      writeFile(file.path, file.source, 'utf8'),
    ),
    ...tablerClientOutput.chunkFiles.map((file) =>
      writeFile(file.path, file.source, 'utf8'),
    ),
    writeFile(getSvgIconPath, getSvgIconModule, 'utf8'),
    writeFile(clientPath, clientModule, 'utf8'),
    rm(legacyOutputPath, { force: true }),
  ])

  runBiomeFormat(generatedPaths)

  console.log(
    `Generated icons modules at ${iconsOutputDir} (iconoir=${iconoirIcons.length}, lucide=${lucideIcons.length}, phosphor=${phosphorIcons.length}, tabler=${tablerIcons.length})`,
  )
}

function runBiomeFormat(paths: string[]) {
  const relativePaths = paths.map((filePath) =>
    path.relative(projectRoot, filePath),
  )
  const formatResult =
    process.platform === 'win32'
      ? spawnSync(
          'cmd.exe',
          [
            '/d',
            '/s',
            '/c',
            `yarn biome format --write ${relativePaths.join(' ')}`,
          ],
          {
            cwd: projectRoot,
            stdio: 'inherit',
          },
        )
      : spawnSync('yarn', ['biome', 'format', '--write', ...relativePaths], {
          cwd: projectRoot,
          stdio: 'inherit',
        })
  if (formatResult.status !== 0) {
    throw new Error('Biome format failed for generated icon files')
  }
}

function chunkIcons(
  icons: GeneratedIcon[],
  chunkSize: number,
): GeneratedIcon[][] {
  const chunks: GeneratedIcon[][] = []
  for (let index = 0; index < icons.length; index += chunkSize) {
    chunks.push(icons.slice(index, index + chunkSize))
  }
  return chunks
}

function toClientExportName(
  provider: IconProviderName,
  iconName: string,
): string {
  const normalized = iconName.replace(/[^a-zA-Z0-9_]/g, '_')
  const withPrefix = `${provider}_${normalized}`
  if (/^[0-9]/.test(withPrefix)) return `_${withPrefix}`
  return withPrefix
}

main().catch((error) => {
  console.error('Icon generation failed:', error)
  process.exit(1)
})
