// This file is generated by scripts/generate-icons.ts. Do not edit manually.

export * from './iconoir.client.generated'
export * from './lucide.client.generated'
export * from './phosphor.client.generated'
export * from './tabler.client.generated'
