// This file is generated by scripts/generate-icons.ts. Do not edit manually.

import { ICONOIR_ICONS, type IconoirIconName } from './iconoir.generated'
import { LUCIDE_ICONS, type LucideIconName } from './lucide.generated'

export type AvailableIconNames =
  | IconoirIconName
  | LucideIconName
  | (string & {})

const SVG_ICONS: Record<AvailableIconNames, string> = {
  ...ICONOIR_ICONS,
  ...LUCIDE_ICONS,
}

export function getSvgIcon(name: AvailableIconNames): string {
  const icon = SVG_ICONS[name]
  if (!icon) throw new Error(`Unknown icon: ${name}`)
  return icon
}
