// This file is generated by scripts/generate-icons.ts. Do not edit manually.

export * from './tabler.client.chunk-0.generated'
export * from './tabler.client.chunk-1.generated'
export * from './tabler.client.chunk-2.generated'
export * from './tabler.client.chunk-3.generated'
export * from './tabler.client.chunk-4.generated'
export * from './tabler.client.chunk-5.generated'
export * from './tabler.client.chunk-6.generated'
