// This file is generated by scripts/generate-icons.ts. Do not edit manually.

export const tabler_world_down =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-world-down" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M20.986 12.509a9 9 0 1 0 -8.455 8.476" /><path d="M3.6 9h16.8" /><path d="M3.6 15h10.9" /><path d="M11.5 3a17 17 0 0 0 0 18" /><path d="M12.5 3c2.313 3.706 3.07 7.857 2.27 12" /><path d="M19 16v6" /><path d="M22 19l-3 3l-3 -3" /></svg>'
export const tabler_world_download =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-world-download" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M21 12a9 9 0 1 0 -9 9" /><path d="M3.6 9h16.8" /><path d="M3.6 15h8.4" /><path d="M11.578 3a17 17 0 0 0 0 18" /><path d="M12.5 3c1.719 2.755 2.5 5.876 2.5 9" /><path d="M18 14v7m-3 -3l3 3l3 -3" /></svg>'
export const tabler_world_exclamation =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-world-exclamation" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M20.986 12.51a9 9 0 1 0 -5.71 7.873" /><path d="M3.6 9h16.8" /><path d="M3.6 15h10.9" /><path d="M11.5 3a17 17 0 0 0 0 18" /><path d="M12.5 3a17 17 0 0 1 0 18" /><path d="M19 16v3" /><path d="M19 22v.01" /></svg>'
export const tabler_world_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-world" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M21.165 16a10 10 0 0 1 -8.434 5.973a1 1 0 0 0 .617 -.444a18 18 0 0 0 2.28 -5.528z" /><path d="M8.372 16a18 18 0 0 0 2.28 5.53a1 1 0 0 0 .616 .443a10 10 0 0 1 -8.433 -5.973z" /><path d="M13.57 16a16 16 0 0 1 -1.57 3.884a16 16 0 0 1 -1.57 -3.884" /><path d="M8.034 10a18 18 0 0 0 0 4h-5.832a10 10 0 0 1 -.002 -4z" /><path d="M13.952 10a16 16 0 0 1 0 4h-3.904a16 16 0 0 1 0 -4z" /><path d="M21.8 10a10.05 10.05 0 0 1 -.002 4h-5.832c.149 -1.329 .149 -2.67 0 -4z" /><path d="M11.267 2.027a1 1 0 0 0 -.615 .444a18 18 0 0 0 -2.28 5.529h-5.54a10.01 10.01 0 0 1 8.334 -5.967z" /><path d="M12 4.116a16 16 0 0 1 1.57 3.885h-3.14c.34 -1.317 .85 -2.6 1.53 -3.817z" /><path d="M12.733 2.026a10.01 10.01 0 0 1 8.435 5.974h-5.54a18 18 0 0 0 -2.28 -5.53a1 1 0 0 0 -.517 -.414z" /></svg>'
export const tabler_world_heart =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-world-heart" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M21 12a9 9 0 1 0 -9.679 8.974" /><path d="M3.6 9h16.8" /><path d="M3.6 15h6.9" /><path d="M11.5 3a17 17 0 0 0 0 18" /><path d="M12.5 3a16.983 16.983 0 0 1 2.556 8.136" /><path d="M18 22l3.35 -3.284a2.143 2.143 0 0 0 .005 -3.071a2.242 2.242 0 0 0 -3.129 -.006l-.224 .22l-.223 -.22a2.242 2.242 0 0 0 -3.128 -.006a2.143 2.143 0 0 0 -.006 3.071l3.355 3.296" /></svg>'
export const tabler_world_latitude =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-world-latitude" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0" /><path d="M4.6 7l14.8 0" /><path d="M3 12l18 0" /><path d="M4.6 17l14.8 0" /></svg>'
export const tabler_world_longitude =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-world-longitude" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0" /><path d="M11.5 3a11.2 11.2 0 0 0 0 18" /><path d="M12.5 3a11.2 11.2 0 0 1 0 18" /><path d="M12 3l0 18" /></svg>'
export const tabler_world_map =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-world-map" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M20 8h-2a2 2 0 0 0 -2 2a2 2 0 1 1 -4 0v-1a2 2 0 0 0 -2 -2h-1a2 2 0 0 1 -2 -2v-.5" /><path d="M3 12h3a2 2 0 0 1 2 2v.5a1.5 1.5 0 0 0 1.5 1.5a1.5 1.5 0 0 1 1.5 1.5v3.25" /><path d="M15 20.5v-3.5a2 2 0 0 1 2 -2h3.5" /><path d="M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0" /></svg>'
export const tabler_world_minus =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-world-minus" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M20.483 15.006a9 9 0 1 0 -7.958 5.978" /><path d="M3.6 9h16.8" /><path d="M3.6 15h16.8" /><path d="M11.5 3a17 17 0 0 0 0 18" /><path d="M12.5 3a16.94 16.94 0 0 1 2.307 12" /><path d="M16 19h6" /></svg>'
export const tabler_world_off =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-world-off" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M5.657 5.615a9 9 0 1 0 12.717 12.739m1.672 -2.322a9 9 0 0 0 -12.066 -12.084" /><path d="M3.6 9h5.4m4 0h7.4" /><path d="M3.6 15h11.4m4 0h1.4" /><path d="M11.5 3a17.001 17.001 0 0 0 -1.493 3.022m-.847 3.145c-.68 4.027 .1 8.244 2.34 11.833" /><path d="M12.5 3a16.982 16.982 0 0 1 2.549 8.005m-.207 3.818a16.979 16.979 0 0 1 -2.342 6.177" /><path d="M3 3l18 18" /></svg>'
export const tabler_world_pause =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-world-pause" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M20.945 12.997a9 9 0 1 0 -7.928 7.945" /><path d="M3.6 9h16.8" /><path d="M3.6 15h9.9" /><path d="M11.5 3a17 17 0 0 0 0 18" /><path d="M12.5 3a16.992 16.992 0 0 1 2.51 10.526" /><path d="M17 17v5" /><path d="M21 17v5" /></svg>'
export const tabler_world_pin =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-world-pin" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M20.972 11.291a9 9 0 1 0 -8.322 9.686" /><path d="M3.6 9h16.8" /><path d="M3.6 15h8.9" /><path d="M11.5 3a17 17 0 0 0 0 18" /><path d="M12.5 3a16.986 16.986 0 0 1 2.578 9.018" /><path d="M21.121 20.121a3 3 0 1 0 -4.242 0c.418 .419 1.125 1.045 2.121 1.879c1.051 -.89 1.759 -1.516 2.121 -1.879" /><path d="M19 18v.01" /></svg>'
export const tabler_world_plus =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-world-plus" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M20.985 12.518a9 9 0 1 0 -8.45 8.466" /><path d="M3.6 9h16.8" /><path d="M3.6 15h11.4" /><path d="M11.5 3a17 17 0 0 0 0 18" /><path d="M12.5 3a16.998 16.998 0 0 1 2.283 12.157" /><path d="M16 19h6" /><path d="M19 16v6" /></svg>'
export const tabler_world_question =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-world-question" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M20.975 11.33a9 9 0 1 0 -5.673 9.043" /><path d="M3.6 9h16.8" /><path d="M3.6 15h9.9" /><path d="M11.5 3a17 17 0 0 0 0 18" /><path d="M12.5 3a16.988 16.988 0 0 1 2.57 9.518m-1.056 5.403a17 17 0 0 1 -1.514 3.079" /><path d="M19 22v.01" /><path d="M19 19a2.003 2.003 0 0 0 .914 -3.782a1.98 1.98 0 0 0 -2.414 .483" /></svg>'
export const tabler_world_search =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-world-search" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M21 12a9 9 0 1 0 -9 9" /><path d="M3.6 9h16.8" /><path d="M3.6 15h7.9" /><path d="M11.5 3a17 17 0 0 0 0 18" /><path d="M12.5 3a16.984 16.984 0 0 1 2.574 8.62" /><path d="M15 18a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" /><path d="M20.2 20.2l1.8 1.8" /></svg>'
export const tabler_world_share =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-world-share" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M20.94 13.045a9 9 0 1 0 -8.953 7.955" /><path d="M3.6 9h16.8" /><path d="M3.6 15h9.4" /><path d="M11.5 3a17 17 0 0 0 0 18" /><path d="M12.5 3a16.991 16.991 0 0 1 2.529 10.294" /><path d="M16 22l5 -5" /><path d="M21 21.5v-4.5h-4.5" /></svg>'
export const tabler_world_star =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-world-star" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M21 12a9 9 0 1 0 -9.968 8.948" /><path d="M3.6 9h16.8" /><path d="M3.6 15h6.4" /><path d="M11.5 3a17.001 17.001 0 0 0 -1.886 13.802" /><path d="M12.5 3a16.982 16.982 0 0 1 2.549 8.01" /><path d="M17.8 20.817l-2.172 1.138a.392 .392 0 0 1 -.568 -.41l.415 -2.411l-1.757 -1.707a.389 .389 0 0 1 .217 -.665l2.428 -.352l1.086 -2.193a.392 .392 0 0 1 .702 0l1.086 2.193l2.428 .352a.39 .39 0 0 1 .217 .665l-1.757 1.707l.414 2.41a.39 .39 0 0 1 -.567 .411l-2.172 -1.138" /></svg>'
export const tabler_world_up =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-world-up" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M20.985 12.52a9 9 0 1 0 -8.451 8.463" /><path d="M3.6 9h16.8" /><path d="M3.6 15h10.9" /><path d="M11.5 3a17 17 0 0 0 0 18" /><path d="M12.5 3a16.996 16.996 0 0 1 2.391 11.512" /><path d="M19 22v-6" /><path d="M22 19l-3 -3l-3 3" /></svg>'
export const tabler_world_upload =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-world-upload" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M21 12a9 9 0 1 0 -9 9" /><path d="M3.6 9h16.8" /><path d="M3.6 15h8.4" /><path d="M11.578 3a17 17 0 0 0 0 18" /><path d="M12.5 3c1.719 2.755 2.5 5.876 2.5 9" /><path d="M18 21v-7m3 3l-3 -3l-3 3" /></svg>'
export const tabler_world_www =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-world-www" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M19.5 7a9 9 0 0 0 -7.5 -4a8.991 8.991 0 0 0 -7.484 4" /><path d="M11.5 3a16.989 16.989 0 0 0 -1.826 4" /><path d="M12.5 3a16.989 16.989 0 0 1 1.828 4" /><path d="M19.5 17a9 9 0 0 1 -7.5 4a8.991 8.991 0 0 1 -7.484 -4" /><path d="M11.5 21a16.989 16.989 0 0 1 -1.826 -4" /><path d="M12.5 21a16.989 16.989 0 0 0 1.828 -4" /><path d="M2 10l1 4l1.5 -4l1.5 4l1 -4" /><path d="M17 10l1 4l1.5 -4l1.5 4l1 -4" /><path d="M9.5 10l1 4l1.5 -4l1.5 4l1 -4" /></svg>'
export const tabler_world_x =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-world-x" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M20.929 13.131a9 9 0 1 0 -8.931 7.869" /><path d="M3.6 9h16.8" /><path d="M3.6 15h9.9" /><path d="M11.5 3a17 17 0 0 0 0 18" /><path d="M12.5 3a16.992 16.992 0 0 1 2.505 10.573" /><path d="M22 22l-5 -5" /><path d="M17 22l5 -5" /></svg>'
export const tabler_wrecking_ball =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-wrecking-ball" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M17 13a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" /><path d="M2 17a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" /><path d="M11 17a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" /><path d="M13 19l-9 0" /><path d="M4 15l9 0" /><path d="M8 12v-5h2a3 3 0 0 1 3 3v5" /><path d="M5 15v-2a1 1 0 0 1 1 -1h7" /><path d="M19 11v-7l-6 7" /></svg>'
export const tabler_writing =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-writing" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M20 17v-12c0 -1.121 -.879 -2 -2 -2s-2 .879 -2 2v12l2 2l2 -2" /><path d="M16 7h4" /><path d="M18 19h-13a2 2 0 1 1 0 -4h4a2 2 0 1 0 0 -4h-3" /></svg>'
export const tabler_writing_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-writing" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M21 8v9a1 1 0 0 1 -.293 .707l-2 2a1 1 0 0 1 -.112 .097l-.11 .071l-.114 .054l-.105 .035l-.149 .03l-.117 .006h-13a3 3 0 0 1 0 -6h4a1 1 0 0 0 0 -2h-3a1 1 0 0 1 0 -2h3a3 3 0 0 1 0 6h-4a1 1 0 0 0 0 2h10.585l-.292 -.293a1 1 0 0 1 -.293 -.707v-9zm-3 -6c1.673 0 3 1.327 3 3v1h-6v-1c0 -1.673 1.327 -3 3 -3" /></svg>'
export const tabler_writing_off =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-writing-off" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M16 7h4" /><path d="M16 16v1l2 2l.5 -.5m1.5 -2.5v-11c0 -1.121 -.879 -2 -2 -2s-2 .879 -2 2v7" /><path d="M18 19h-13a2 2 0 1 1 0 -4h4a2 2 0 1 0 0 -4h-3" /><path d="M3 3l18 18" /></svg>'
export const tabler_writing_sign =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-writing-sign" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 19c3.333 -2 5 -4 5 -6c0 -3 -1 -3 -2 -3s-2.032 1.085 -2 3c.034 2.048 1.658 2.877 2.5 4c1.5 2 2.5 2.5 3.5 1c.667 -1 1.167 -1.833 1.5 -2.5c1 2.333 2.333 3.5 4 3.5h2.5" /><path d="M20 17v-12c0 -1.121 -.879 -2 -2 -2s-2 .879 -2 2v12l2 2l2 -2" /><path d="M16 7h4" /></svg>'
export const tabler_writing_sign_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-writing-sign" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M6 11c-.483 0 -1.021 .725 -1 1.983c.013 .783 .29 1.3 1.035 2.07l.107 .107l.101 -.134c.466 -.643 .714 -1.266 .752 -1.864l.005 -.162l-.003 -.563c-.017 -1.284 -.13 -1.422 -.807 -1.436zm12 -9c1.673 0 3 1.327 3 3v1h-6v-1c0 -1.673 1.327 -3 3 -3m2.707 15.707l-2 2l-.08 .071l-.043 .034l-.084 .054l-.103 .052l-.084 .032l-.08 .023l-.143 .023l-.071 .004h-2.519c-1.616 0 -2.954 -.83 -4.004 -2.393l-.026 -.04l-.273 .431l-.365 .557c-1.356 2.034 -2.942 1.691 -4.7 -.41l-.064 -.076l-.176 .147q -.897 .727 -2.045 1.438l-.332 .203a1 1 0 1 1 -1.03 -1.714a19 19 0 0 0 2.17 -1.498l.078 -.065l-.147 -.15c-.998 -1.033 -1.498 -1.904 -1.576 -3.157l-.01 -.256c-.038 -2.273 1.257 -4.017 3 -4.017c2.052 0 3 .948 3 4c0 1.218 -.47 2.392 -1.392 3.532l-.11 .13l.28 .36c.784 .985 .994 .992 1.343 .492l.047 -.069q .97 -1.456 1.437 -2.392a1 1 0 0 1 1.814 .053c.858 2.002 1.878 2.894 3.081 2.894l.085 -.001l-.292 -.292a1 1 0 0 1 -.293 -.707v-9h6v9a1 1 0 0 1 -.293 .707" /></svg>'
export const tabler_writing_sign_off =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-writing-sign-off" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 19c3.333 -2 5 -4 5 -6c0 -3 -1 -3 -2 -3s-2.032 1.085 -2 3c.034 2.048 1.658 2.877 2.5 4c1.5 2 2.5 2.5 3.5 1c.667 -1 1.167 -1.833 1.5 -2.5c1 2.333 2.333 3.5 4 3.5h2.5" /><path d="M16 16v1l2 2l.5 -.5m1.5 -2.5v-11c0 -1.121 -.879 -2 -2 -2s-2 .879 -2 2v7" /><path d="M16 7h4" /><path d="M3 3l18 18" /></svg>'
export const tabler_x =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-x" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M18 6l-12 12" /><path d="M6 6l12 12" /></svg>'
export const tabler_x_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-x" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M6.707 5.293l5.293 5.292l5.293 -5.292a1 1 0 0 1 1.414 1.414l-5.292 5.293l5.292 5.293a1 1 0 0 1 -1.414 1.414l-5.293 -5.292l-5.293 5.292a1 1 0 1 1 -1.414 -1.414l5.292 -5.293l-5.292 -5.293a1 1 0 0 1 1.414 -1.414" /></svg>'
export const tabler_x_mark =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-x-mark" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M12 16l3.644 3.644a1.21 1.21 0 0 0 1.712 0l2.288 -2.288a1.21 1.21 0 0 0 0 -1.712l-3.644 -3.644l3.644 -3.644a1.21 1.21 0 0 0 0 -1.712l-2.288 -2.288a1.21 1.21 0 0 0 -1.712 0l-3.644 3.644l-3.644 -3.644a1.21 1.21 0 0 0 -1.712 0l-2.288 2.288a1.21 1.21 0 0 0 0 1.712l3.644 3.644l-3.644 3.644a1.21 1.21 0 0 0 0 1.712l2.288 2.288a1.21 1.21 0 0 0 1.712 0l3.644 -3.644" /></svg>'
export const tabler_x_power_y =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-x-power-y" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M15 3l3 5.063" /><path d="M5 12l6 6" /><path d="M5 18l6 -6" /><path d="M21 3l-4.8 9" /></svg>'
export const tabler_xbox_a =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-xbox-a" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M12 21a9 9 0 0 0 9 -9a9 9 0 0 0 -9 -9a9 9 0 0 0 -9 9a9 9 0 0 0 9 9" /><path d="M15 16l-3 -8l-3 8" /><path d="M14 14h-4" /></svg>'
export const tabler_xbox_a_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-xbox-a" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M12 2c5.523 0 10 4.477 10 10s-4.477 10 -10 10s-10 -4.477 -10 -10s4.477 -10 10 -10m.936 5.649c-.324 -.865 -1.548 -.865 -1.872 0l-3 8a1 1 0 0 0 .585 1.287l.111 .035a1 1 0 0 0 1.176 -.62l.507 -1.351h3.114l.507 1.351a1 1 0 1 0 1.872 -.702zm-.936 3.199l.807 2.152h-1.614z" /></svg>'
export const tabler_xbox_b =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-xbox-b" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M12 21a9 9 0 0 0 9 -9a9 9 0 0 0 -9 -9a9 9 0 0 0 -9 9a9 9 0 0 0 9 9" /><path d="M13 12a2 2 0 1 1 0 4h-3v-4" /><path d="M13 12h-3" /><path d="M13 12a2 2 0 1 0 0 -4h-3v4" /></svg>'
export const tabler_xbox_b_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-xbox-b" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M12 2c5.523 0 10 4.477 10 10s-4.477 10 -10 10s-10 -4.477 -10 -10s4.477 -10 10 -10m1 5h-3a1 1 0 0 0 -1 1v8a1 1 0 0 0 1 1h3a3 3 0 0 0 2.235 -5a3 3 0 0 0 -2.235 -5m0 6a1 1 0 0 1 1 1l-.007 .117a1 1 0 0 1 -.993 .883h-2v-2zm0 -4a1 1 0 0 1 0 2h-2v-2z" /></svg>'
export const tabler_xbox_x =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-xbox-x" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M12 21a9 9 0 0 0 9 -9a9 9 0 0 0 -9 -9a9 9 0 0 0 -9 9a9 9 0 0 0 9 9" /><path d="M9 8l6 8" /><path d="M15 8l-6 8" /></svg>'
export const tabler_xbox_x_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-xbox-x" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M12 2c5.523 0 10 4.477 10 10s-4.477 10 -10 10s-10 -4.477 -10 -10s4.477 -10 10 -10m3.6 5.2a1 1 0 0 0 -1.4 .2l-2.2 2.933l-2.2 -2.933a1 1 0 1 0 -1.6 1.2l2.55 3.4l-2.55 3.4a1 1 0 1 0 1.6 1.2l2.2 -2.933l2.2 2.933a1 1 0 0 0 1.6 -1.2l-2.55 -3.4l2.55 -3.4a1 1 0 0 0 -.2 -1.4" /></svg>'
export const tabler_xbox_y =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-xbox-y" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M12 21a9 9 0 0 0 9 -9a9 9 0 0 0 -9 -9a9 9 0 0 0 -9 9a9 9 0 0 0 9 9" /><path d="M9 8l3 4" /><path d="M15 8l-2.988 3.984l-.012 4.016" /></svg>'
export const tabler_xbox_y_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-xbox-y" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M12 2c5.523 0 10 4.477 10 10s-4.477 10 -10 10s-10 -4.477 -10 -10s4.477 -10 10 -10m3.6 5.2a1 1 0 0 0 -1.4 .2l-2.2 2.933l-2.2 -2.933a1 1 0 1 0 -1.6 1.2l2.81 3.748l-.01 3.649a1 1 0 0 0 .997 1.003l.117 -.006a1 1 0 0 0 .886 -.991l.01 -3.683l2.79 -3.72a1 1 0 0 0 -.2 -1.4" /></svg>'
export const tabler_xd =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-xd" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M6 8l4 8" /><path d="M6 16l4 -8" /><path d="M14 8v8h2a2 2 0 0 0 2 -2v-4a2 2 0 0 0 -2 -2h-2" /></svg>'
export const tabler_xxx =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-xxx" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M10 8l4 8" /><path d="M10 16l4 -8" /><path d="M17 8l4 8" /><path d="M17 16l4 -8" /><path d="M3 8l4 8" /><path d="M3 16l4 -8" /></svg>'
export const tabler_yin_yang =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-yin-yang" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0" /><path d="M12 3a4.5 4.5 0 0 0 0 9a4.5 4.5 0 0 1 0 9" /><path d="M11.5 7.5a.5 .5 0 1 0 1 0a.5 .5 0 1 0 -1 0" fill="currentColor" /><path d="M11.5 16.5a.5 .5 0 1 0 1 0a.5 .5 0 1 0 -1 0" fill="currentColor" /></svg>'
export const tabler_yin_yang_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-yin-yang" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M17 3.34a10 10 0 1 1 -14.995 8.984l-.005 -.324l.005 -.324a10 10 0 0 1 14.995 -8.336zm-9 1.732a8 8 0 0 0 4 14.928l.2 -.005a4 4 0 0 0 0 -7.99l-.2 -.005a4 4 0 0 1 -.2 -7.995l.2 -.005a7.995 7.995 0 0 0 -4 1.072zm4 1.428a1.5 1.5 0 1 0 0 3a1.5 1.5 0 0 0 0 -3" /><path d="M12 14.5a1.5 1.5 0 1 1 0 3a1.5 1.5 0 0 1 0 -3" /></svg>'
export const tabler_yoga =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-yoga" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M11 4a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" /><path d="M4 20h4l1.5 -3" /><path d="M17 20l-1 -5h-5l1 -7" /><path d="M4 10l4 -1l4 -1l4 1.5l4 1.5" /></svg>'
export const tabler_zeppelin =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zeppelin" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M13.5 4c4.694 0 8.5 2.686 8.5 6s-3.806 6 -8.5 6c-2.13 0 -4.584 -.926 -7.364 -2.777l-2.136 1.777v-3.33a46.07 46.07 0 0 1 -2 -1.67a46.07 46.07 0 0 1 2 -1.67v-3.33l2.135 1.778c2.78 -1.852 5.235 -2.778 7.365 -2.778" /><path d="M10 15.5v4.5h6v-4" /></svg>'
export const tabler_zeppelin_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-zeppelin" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M13.5 3c5.187 0 9.5 3.044 9.5 7c0 3.017 -2.508 5.503 -6 6.514v3.486a1 1 0 0 1 -1 1h-6a1 1 0 0 1 -1 -1v-4.046a21 21 0 0 1 -2.66 -1.411l-.13 -.082l-1.57 1.308a1 1 0 0 1 -1.634 -.656l-.006 -.113v-2.851l-.31 -.25a47 47 0 0 1 -.682 -.568l-.67 -.582a1 1 0 0 1 0 -1.498a47 47 0 0 1 1.351 -1.151l.311 -.25v-2.85a1 1 0 0 1 1.55 -.836l.09 .068l1.57 1.307l.128 -.08c2.504 -1.553 4.784 -2.378 6.853 -2.453zm-2.499 13.657l-.001 2.343h4l.001 -2.086q -.735 .086 -1.501 .086a9.6 9.6 0 0 1 -2.13 -.252z" /></svg>'
export const tabler_zeppelin_off =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zeppelin-off" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M15.773 15.783c-.723 .141 -1.486 .217 -2.273 .217c-2.13 0 -4.584 -.926 -7.364 -2.777l-2.136 1.777v-3.33a46.07 46.07 0 0 1 -2 -1.67a46.07 46.07 0 0 1 2 -1.67v-3.33l2.135 1.778c.13 -.087 .261 -.172 .39 -.256m2.564 -1.42c1.601 -.735 3.071 -1.102 4.411 -1.102c4.694 0 8.5 2.686 8.5 6c0 1.919 -1.276 3.627 -3.261 4.725" /><path d="M10 15.5v4.5h6v-4" /><path d="M3 3l18 18" /></svg>'
export const tabler_zero_config =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zero-config" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 12a8 8 0 1 0 16 0a8 8 0 1 0 -16 0" /><path d="M3 21l18 -18" /></svg>'
export const tabler_zip =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zip" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M16 16v-8h2a2 2 0 1 1 0 4h-2" /><path d="M12 8v8" /><path d="M4 8h4l-4 8h4" /></svg>'
export const tabler_zodiac_aquarius =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-aquarius" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10l3 -3l3 3l3 -3l3 3l3 -3l3 3" /><path d="M3 17l3 -3l3 3l3 -3l3 3l3 -3l3 3" /></svg>'
export const tabler_zodiac_aries =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-aries" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M12 5a5 5 0 1 0 -4 8" /><path d="M16 13a5 5 0 1 0 -4 -8" /><path d="M12 21l0 -16" /></svg>'
export const tabler_zodiac_cancer =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-cancer" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" /><path d="M15 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" /><path d="M3 12a10 6.5 0 0 1 14 -6.5" /><path d="M21 12a10 6.5 0 0 1 -14 6.5" /></svg>'
export const tabler_zodiac_capricorn =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-capricorn" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 4a3 3 0 0 1 3 3v9" /><path d="M7 7a3 3 0 0 1 6 0v11a3 3 0 0 1 -3 3" /><path d="M13 17a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" /></svg>'
export const tabler_zodiac_gemini =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-gemini" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 3a21 21 0 0 0 18 0" /><path d="M3 21a21 21 0 0 1 18 0" /><path d="M7 4.5l0 15" /><path d="M17 4.5l0 15" /></svg>'
export const tabler_zodiac_leo =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-leo" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M13 17a4 4 0 1 0 8 0" /><path d="M3 16a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" /><path d="M7 7a4 4 0 1 0 8 0a4 4 0 1 0 -8 0" /><path d="M7 7c0 3 2 5 2 9" /><path d="M15 7c0 4 -2 6 -2 10" /></svg>'
export const tabler_zodiac_libra =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-libra" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M5 20l14 0" /><path d="M5 17h5v-.3a7 7 0 1 1 4 0v.3h5" /></svg>'
export const tabler_zodiac_pisces =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-pisces" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M5 3a21 21 0 0 1 0 18" /><path d="M19 3a21 21 0 0 0 0 18" /><path d="M5 12l14 0" /></svg>'
export const tabler_zodiac_sagittarius =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-sagittarius" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 20l16 -16" /><path d="M13 4h7v7" /><path d="M6.5 12.5l5 5" /></svg>'
export const tabler_zodiac_scorpio =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-scorpio" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 4a2 2 0 0 1 2 2v9" /><path d="M5 6a2 2 0 0 1 4 0v9" /><path d="M9 6a2 2 0 0 1 4 0v10a3 3 0 0 0 3 3h5l-3 -3m0 6l3 -3" /></svg>'
export const tabler_zodiac_taurus =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-taurus" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M6 3a6 6 0 0 0 12 0" /><path d="M6 15a6 6 0 1 0 12 0a6 6 0 1 0 -12 0" /></svg>'
export const tabler_zodiac_virgo =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-virgo" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 4a2 2 0 0 1 2 2v9" /><path d="M5 6a2 2 0 0 1 4 0v9" /><path d="M9 6a2 2 0 0 1 4 0v10a7 5 0 0 0 7 5" /><path d="M12 21a7 5 0 0 0 7 -5v-2a3 3 0 0 0 -6 0" /></svg>'
export const tabler_zoom =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" /><path d="M21 21l-6 -6" /></svg>'
export const tabler_zoom_cancel =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-cancel" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" /><path d="M8 8l4 4" /><path d="M12 8l-4 4" /><path d="M21 21l-6 -6" /></svg>'
export const tabler_zoom_cancel_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-zoom-cancel" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M14 3.072a8 8 0 0 1 2.32 11.834l5.387 5.387a1 1 0 0 1 -1.414 1.414l-5.388 -5.387a8 8 0 0 1 -12.905 -6.32l.005 -.285a8 8 0 0 1 11.995 -6.643m-5.293 4.22a1 1 0 0 0 -1.414 1.415l1.292 1.293l-1.292 1.293a1 1 0 0 0 1.414 1.414l1.293 -1.292l1.293 1.292a1 1 0 0 0 1.414 -1.414l-1.292 -1.293l1.292 -1.293a1 1 0 1 0 -1.414 -1.414l-1.293 1.292z" /></svg>'
export const tabler_zoom_check =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-check" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" /><path d="M21 21l-6 -6" /><path d="M7 10l2 2l4 -4" /></svg>'
export const tabler_zoom_check_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-zoom-check" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M14 3.072a8 8 0 0 1 2.617 11.424l4.944 4.943a1.5 1.5 0 0 1 -2.008 2.225l-.114 -.103l-4.943 -4.944a8 8 0 0 1 -12.49 -6.332l-.006 -.285l.005 -.285a8 8 0 0 1 11.995 -6.643zm-.293 4.22a1 1 0 0 0 -1.414 0l-3.293 3.294l-1.293 -1.293l-.094 -.083a1 1 0 0 0 -1.32 1.497l2 2l.094 .083a1 1 0 0 0 1.32 -.083l4 -4l.083 -.094a1 1 0 0 0 -.083 -1.32z" /></svg>'
export const tabler_zoom_code =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-code" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" /><path d="M21 21l-6 -6" /><path d="M8 8l-2 2l2 2" /><path d="M12 8l2 2l-2 2" /></svg>'
export const tabler_zoom_code_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-zoom-code" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M14 3.072a8 8 0 0 1 2.32 11.834l5.387 5.387a1 1 0 0 1 -1.414 1.414l-5.388 -5.387a8 8 0 0 1 -12.905 -6.32l.005 -.285a8 8 0 0 1 11.995 -6.643m-5.293 4.22a1 1 0 0 0 -1.414 0l-2 2a1 1 0 0 0 0 1.415l2 2a1 1 0 0 0 1.414 0l.083 -.094a1 1 0 0 0 -.083 -1.32l-1.292 -1.293l1.292 -1.293a1 1 0 0 0 0 -1.414m4 0a1 1 0 0 0 -1.414 0l-.083 .095a1 1 0 0 0 .083 1.32l1.292 1.292l-1.292 1.293a1 1 0 0 0 1.414 1.414l2 -2a1 1 0 0 0 0 -1.414z" /></svg>'
export const tabler_zoom_exclamation =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-exclamation" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" /><path d="M21 21l-6 -6" /><path d="M10 13v.01" /><path d="M10 7v3" /></svg>'
export const tabler_zoom_exclamation_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-zoom-exclamation" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M14 3.072a8 8 0 0 1 2.32 11.834l5.387 5.387a1 1 0 0 1 -1.414 1.414l-5.388 -5.387a8 8 0 0 1 -12.905 -6.32l.005 -.285a8 8 0 0 1 11.995 -6.643m-4 8.928a1 1 0 0 0 -1 1l.007 .127a1 1 0 0 0 1.993 -.117l-.007 -.127a1 1 0 0 0 -.993 -.883m0 -6a1 1 0 0 0 -1 1v3a1 1 0 0 0 2 0v-3a1 1 0 0 0 -1 -1" /></svg>'
export const tabler_zoom_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-zoom" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M14 3.072a8 8 0 0 1 2.617 11.424l4.944 4.943a1.5 1.5 0 0 1 -2.008 2.225l-.114 -.103l-4.943 -4.944a8 8 0 0 1 -12.49 -6.332l-.006 -.285l.005 -.285a8 8 0 0 1 11.995 -6.643z" /></svg>'
export const tabler_zoom_in =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-in" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" /><path d="M7 10l6 0" /><path d="M10 7l0 6" /><path d="M21 21l-6 -6" /></svg>'
export const tabler_zoom_in_area =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-in-area" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M15 13v4" /><path d="M13 15h4" /><path d="M10 15a5 5 0 1 0 10 0a5 5 0 1 0 -10 0" /><path d="M22 22l-3 -3" /><path d="M6 18h-1a2 2 0 0 1 -2 -2v-1" /><path d="M3 11v-1" /><path d="M3 6v-1a2 2 0 0 1 2 -2h1" /><path d="M10 3h1" /><path d="M15 3h1a2 2 0 0 1 2 2v1" /></svg>'
export const tabler_zoom_in_area_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-zoom-in-area" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M15 9a6 6 0 0 1 4.891 9.476l2.816 2.817a1 1 0 0 1 -1.32 1.497l-.094 -.083l-2.817 -2.816a6 6 0 0 1 -9.472 -4.666l-.004 -.225l.004 -.225a6 6 0 0 1 5.996 -5.775zm0 3a1 1 0 0 0 -.993 .883l-.007 .117v1h-1l-.117 .007a1 1 0 0 0 0 1.986l.117 .007h1v1l.007 .117a1 1 0 0 0 1.986 0l.007 -.117v-1h1l.117 -.007a1 1 0 0 0 0 -1.986l-.117 -.007h-1v-1l-.007 -.117a1 1 0 0 0 -.993 -.883z" /><path d="M3 14a1 1 0 0 1 .993 .883l.007 .117v1a1 1 0 0 0 .883 .993l.117 .007h1a1 1 0 0 1 .117 1.993l-.117 .007h-1a3 3 0 0 1 -2.995 -2.824l-.005 -.176v-1a1 1 0 0 1 1 -1z" /><path d="M3 9a1 1 0 0 1 .993 .883l.007 .117v1a1 1 0 0 1 -1.993 .117l-.007 -.117v-1a1 1 0 0 1 1 -1z" /><path d="M6 2a1 1 0 0 1 .117 1.993l-.117 .007h-1a1 1 0 0 0 -.993 .883l-.007 .117v1a1 1 0 0 1 -1.993 .117l-.007 -.117v-1a3 3 0 0 1 2.824 -2.995l.176 -.005h1z" /><path d="M11 2a1 1 0 0 1 .117 1.993l-.117 .007h-1a1 1 0 0 1 -.117 -1.993l.117 -.007h1z" /><path d="M16 2a3 3 0 0 1 2.995 2.824l.005 .176v1a1 1 0 0 1 -1.993 .117l-.007 -.117v-1a1 1 0 0 0 -.883 -.993l-.117 -.007h-1a1 1 0 0 1 -.117 -1.993l.117 -.007h1z" /></svg>'
export const tabler_zoom_in_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-zoom-in" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M14 3.072a8 8 0 0 1 2.617 11.424l4.944 4.943a1.5 1.5 0 0 1 -2.008 2.225l-.114 -.103l-4.943 -4.944a8 8 0 0 1 -12.49 -6.332l-.006 -.285l.005 -.285a8 8 0 0 1 11.995 -6.643zm-4 2.928a1 1 0 0 0 -.993 .883l-.007 .117v2h-2l-.117 .007a1 1 0 0 0 0 1.986l.117 .007h2v2l.007 .117a1 1 0 0 0 1.986 0l.007 -.117v-2h2l.117 -.007a1 1 0 0 0 0 -1.986l-.117 -.007h-2v-2l-.007 -.117a1 1 0 0 0 -.993 -.883z" /></svg>'
export const tabler_zoom_money =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-money" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" /><path d="M21 21l-6 -6" /><path d="M12 7h-2.5a1.5 1.5 0 0 0 0 3h1a1.5 1.5 0 0 1 0 3h-2.5" /><path d="M10 13v1m0 -8v1" /></svg>'
export const tabler_zoom_money_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-zoom-money" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M14 3.072a8 8 0 0 1 2.32 11.834l5.387 5.387a1 1 0 0 1 -1.414 1.414l-5.388 -5.387a8 8 0 0 1 -12.905 -6.32l.005 -.285a8 8 0 0 1 11.995 -6.643m-2 2.928h-2.5a2.5 2.5 0 0 0 0 5h1a.5 .5 0 1 1 0 1h-2.5a1 1 0 0 0 0 2h2.5a2.5 2.5 0 1 0 0 -5h-1a.5 .5 0 0 1 0 -1h2.5a1 1 0 0 0 0 -2" /></svg>'
export const tabler_zoom_out =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-out" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" /><path d="M7 10l6 0" /><path d="M21 21l-6 -6" /></svg>'
export const tabler_zoom_out_area =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-out-area" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M13 15h4" /><path d="M10 15a5 5 0 1 0 10 0a5 5 0 1 0 -10 0" /><path d="M22 22l-3 -3" /><path d="M6 18h-1a2 2 0 0 1 -2 -2v-1" /><path d="M3 11v-1" /><path d="M3 6v-1a2 2 0 0 1 2 -2h1" /><path d="M10 3h1" /><path d="M15 3h1a2 2 0 0 1 2 2v1" /></svg>'
export const tabler_zoom_out_area_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-zoom-out-area" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M15 9a6 6 0 0 1 4.891 9.476l2.816 2.817a1 1 0 0 1 -1.414 1.414l-2.817 -2.816a6 6 0 0 1 -9.476 -4.891l.004 -.225a6 6 0 0 1 5.996 -5.775m2 5h-4a1 1 0 0 0 0 2h4a1 1 0 0 0 0 -2m-14 0a1 1 0 0 1 1 1v1a1 1 0 0 0 1 1h1a1 1 0 0 1 0 2h-1a3 3 0 0 1 -3 -3v-1a1 1 0 0 1 1 -1m0 -5a1 1 0 0 1 1 1v1a1 1 0 0 1 -2 0v-1a1 1 0 0 1 1 -1m3 -7a1 1 0 1 1 0 2h-1a1 1 0 0 0 -1 1v1a1 1 0 1 1 -2 0v-1a3 3 0 0 1 3 -3zm5 0a1 1 0 0 1 0 2h-1a1 1 0 1 1 0 -2zm5 0a3 3 0 0 1 3 3v1a1 1 0 0 1 -2 0v-1a1 1 0 0 0 -1 -1h-1a1 1 0 0 1 0 -2z" /></svg>'
export const tabler_zoom_out_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-zoom-out" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M14 3.072a8 8 0 0 1 2.617 11.424l4.944 4.943a1.5 1.5 0 0 1 -2.008 2.225l-.114 -.103l-4.943 -4.944a8 8 0 0 1 -12.49 -6.332l-.006 -.285l.005 -.285a8 8 0 0 1 11.995 -6.643zm-1 5.928h-6l-.117 .007a1 1 0 0 0 0 1.986l.117 .007h6l.117 -.007a1 1 0 0 0 0 -1.986l-.117 -.007z" /></svg>'
export const tabler_zoom_pan =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-pan" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M9 12a3 3 0 1 0 6 0a3 3 0 0 0 -6 0" /><path d="M17 17l-2.5 -2.5" /><path d="M10 4l2 -2l2 2" /><path d="M20 10l2 2l-2 2" /><path d="M4 10l-2 2l2 2" /><path d="M10 20l2 2l2 -2" /></svg>'
export const tabler_zoom_pan_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-zoom-pan" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M12 8a4 4 0 0 1 3.447 6.031l2.26 2.262a1 1 0 0 1 -1.414 1.414l-2.262 -2.26a4 4 0 0 1 -6.031 -3.447l.005 -.2a4 4 0 0 1 3.995 -3.8" /><path d="M11.293 1.293a1 1 0 0 1 1.414 0l2 2a1 1 0 1 1 -1.414 1.414l-1.293 -1.292l-1.293 1.292a1 1 0 0 1 -1.32 .083l-.094 -.083a1 1 0 0 1 0 -1.414z" /><path d="M19.293 9.293a1 1 0 0 1 1.414 0l2 2a1 1 0 0 1 0 1.414l-2 2a1 1 0 0 1 -1.414 -1.414l1.292 -1.293l-1.292 -1.293a1 1 0 0 1 -.083 -1.32z" /><path d="M3.293 9.293a1 1 0 1 1 1.414 1.414l-1.292 1.293l1.292 1.293a1 1 0 0 1 .083 1.32l-.083 .094a1 1 0 0 1 -1.414 0l-2 -2a1 1 0 0 1 0 -1.414z" /><path d="M9.293 19.293a1 1 0 0 1 1.414 0l1.293 1.292l1.294 -1.292a1 1 0 0 1 1.32 -.083l.094 .083a1 1 0 0 1 0 1.414l-2 2a1 1 0 0 1 -1.414 0l-2 -2a1 1 0 0 1 0 -1.414" /></svg>'
export const tabler_zoom_question =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-question" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" /><path d="M21 21l-6 -6" /><path d="M10 13l0 .01" /><path d="M10 10a1.5 1.5 0 1 0 -1.14 -2.474" /></svg>'
export const tabler_zoom_question_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-zoom-question" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M14 3.072a8 8 0 0 1 2.32 11.834l5.387 5.387a1 1 0 0 1 -1.414 1.414l-5.388 -5.387a8 8 0 0 1 -12.905 -6.32l.005 -.285a8 8 0 0 1 11.995 -6.643m-4 8.928a1 1 0 0 0 -.993 .883l-.007 .127a1 1 0 0 0 1.993 .117l.007 -.127a1 1 0 0 0 -1 -1m-1.9 -5.123a1 1 0 0 0 1.433 1.389l.088 -.09a.5 .5 0 1 1 .379 .824a1 1 0 0 0 -.002 2a2.5 2.5 0 1 0 -1.9 -4.123" /></svg>'
export const tabler_zoom_replace =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-replace" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M21 21l-6 -6" /><path d="M3.291 8a7 7 0 0 1 5.077 -4.806a7.021 7.021 0 0 1 8.242 4.403" /><path d="M17 4v4h-4" /><path d="M16.705 12a7 7 0 0 1 -5.074 4.798a7.021 7.021 0 0 1 -8.241 -4.403" /><path d="M3 16v-4h4" /></svg>'
export const tabler_zoom_reset =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-reset" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M21 21l-6 -6" /><path d="M3.268 12.043a7.017 7.017 0 0 0 6.634 4.957a7.012 7.012 0 0 0 7.043 -6.131a7 7 0 0 0 -5.314 -7.672a7.021 7.021 0 0 0 -8.241 4.403" /><path d="M3 4v4h4" /></svg>'
export const tabler_zoom_scan =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-scan" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 8v-2a2 2 0 0 1 2 -2h2" /><path d="M4 16v2a2 2 0 0 0 2 2h2" /><path d="M16 4h2a2 2 0 0 1 2 2v2" /><path d="M16 20h2a2 2 0 0 0 2 -2v-2" /><path d="M8 11a3 3 0 1 0 6 0a3 3 0 0 0 -6 0" /><path d="M16 16l-2.5 -2.5" /></svg>'
export const tabler_zoom_scan_filled =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-filled icon-tabler-zoom-scan" fill="currentColor" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 15a1 1 0 0 1 1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 1 0 2h-2a3 3 0 0 1 -3 -3v-2a1 1 0 0 1 1 -1" /><path d="M20 15a1 1 0 0 1 1 1v2a3 3 0 0 1 -3 3h-2a1 1 0 0 1 0 -2h2a1 1 0 0 0 1 -1v-2a1 1 0 0 1 1 -1" /><path d="M11 7a4 4 0 0 1 3.446 6.031l2.261 2.262a1 1 0 0 1 -1.414 1.414l-2.262 -2.26l-.031 .017a4 4 0 0 1 -6 -3.464l.005 -.2a4 4 0 0 1 3.995 -3.8" /><path d="M8 3a1 1 0 1 1 0 2h-2a1 1 0 0 0 -1 1v2a1 1 0 1 1 -2 0v-2a3 3 0 0 1 3 -3z" /><path d="M18 3a3 3 0 0 1 3 3v2a1 1 0 0 1 -2 0v-2a1 1 0 0 0 -1 -1h-2a1 1 0 0 1 0 -2z" /></svg>'
export const tabler_zzz =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zzz" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 12h6l-6 8h6" /><path d="M14 4h6l-6 8h6" /></svg>'
export const tabler_zzz_off =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zzz-off" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 12h6l-6 8h6" /><path d="M14 4h6l-5.146 6.862m1.146 1.138h4" /><path d="M3 3l18 18" /></svg>'

export type TablerIconNameChunk6 =
  | 'tabler:world-down'
  | 'tabler:world-download'
  | 'tabler:world-exclamation'
  | 'tabler:world-filled'
  | 'tabler:world-heart'
  | 'tabler:world-latitude'
  | 'tabler:world-longitude'
  | 'tabler:world-map'
  | 'tabler:world-minus'
  | 'tabler:world-off'
  | 'tabler:world-pause'
  | 'tabler:world-pin'
  | 'tabler:world-plus'
  | 'tabler:world-question'
  | 'tabler:world-search'
  | 'tabler:world-share'
  | 'tabler:world-star'
  | 'tabler:world-up'
  | 'tabler:world-upload'
  | 'tabler:world-www'
  | 'tabler:world-x'
  | 'tabler:wrecking-ball'
  | 'tabler:writing'
  | 'tabler:writing-filled'
  | 'tabler:writing-off'
  | 'tabler:writing-sign'
  | 'tabler:writing-sign-filled'
  | 'tabler:writing-sign-off'
  | 'tabler:x'
  | 'tabler:x-filled'
  | 'tabler:x-mark'
  | 'tabler:x-power-y'
  | 'tabler:xbox-a'
  | 'tabler:xbox-a-filled'
  | 'tabler:xbox-b'
  | 'tabler:xbox-b-filled'
  | 'tabler:xbox-x'
  | 'tabler:xbox-x-filled'
  | 'tabler:xbox-y'
  | 'tabler:xbox-y-filled'
  | 'tabler:xd'
  | 'tabler:xxx'
  | 'tabler:yin-yang'
  | 'tabler:yin-yang-filled'
  | 'tabler:yoga'
  | 'tabler:zeppelin'
  | 'tabler:zeppelin-filled'
  | 'tabler:zeppelin-off'
  | 'tabler:zero-config'
  | 'tabler:zip'
  | 'tabler:zodiac-aquarius'
  | 'tabler:zodiac-aries'
  | 'tabler:zodiac-cancer'
  | 'tabler:zodiac-capricorn'
  | 'tabler:zodiac-gemini'
  | 'tabler:zodiac-leo'
  | 'tabler:zodiac-libra'
  | 'tabler:zodiac-pisces'
  | 'tabler:zodiac-sagittarius'
  | 'tabler:zodiac-scorpio'
  | 'tabler:zodiac-taurus'
  | 'tabler:zodiac-virgo'
  | 'tabler:zoom'
  | 'tabler:zoom-cancel'
  | 'tabler:zoom-cancel-filled'
  | 'tabler:zoom-check'
  | 'tabler:zoom-check-filled'
  | 'tabler:zoom-code'
  | 'tabler:zoom-code-filled'
  | 'tabler:zoom-exclamation'
  | 'tabler:zoom-exclamation-filled'
  | 'tabler:zoom-filled'
  | 'tabler:zoom-in'
  | 'tabler:zoom-in-area'
  | 'tabler:zoom-in-area-filled'
  | 'tabler:zoom-in-filled'
  | 'tabler:zoom-money'
  | 'tabler:zoom-money-filled'
  | 'tabler:zoom-out'
  | 'tabler:zoom-out-area'
  | 'tabler:zoom-out-area-filled'
  | 'tabler:zoom-out-filled'
  | 'tabler:zoom-pan'
  | 'tabler:zoom-pan-filled'
  | 'tabler:zoom-question'
  | 'tabler:zoom-question-filled'
  | 'tabler:zoom-replace'
  | 'tabler:zoom-reset'
  | 'tabler:zoom-scan'
  | 'tabler:zoom-scan-filled'
  | 'tabler:zzz'
  | 'tabler:zzz-off'
