// This file is generated by scripts/generate-icons.ts. Do not edit manually.

export const tabler_xbox_x =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-xbox-x" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M12 21a9 9 0 0 0 9 -9a9 9 0 0 0 -9 -9a9 9 0 0 0 -9 9a9 9 0 0 0 9 9" /><path d="M9 8l6 8" /><path d="M15 8l-6 8" /></svg>'
export const tabler_xbox_y =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-xbox-y" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M12 21a9 9 0 0 0 9 -9a9 9 0 0 0 -9 -9a9 9 0 0 0 -9 9a9 9 0 0 0 9 9" /><path d="M9 8l3 4" /><path d="M15 8l-2.988 3.984l-.012 4.016" /></svg>'
export const tabler_xd =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-xd" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M6 8l4 8" /><path d="M6 16l4 -8" /><path d="M14 8v8h2a2 2 0 0 0 2 -2v-4a2 2 0 0 0 -2 -2h-2" /></svg>'
export const tabler_xxx =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-xxx" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M10 8l4 8" /><path d="M10 16l4 -8" /><path d="M17 8l4 8" /><path d="M17 16l4 -8" /><path d="M3 8l4 8" /><path d="M3 16l4 -8" /></svg>'
export const tabler_yin_yang =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-yin-yang" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0" /><path d="M12 3a4.5 4.5 0 0 0 0 9a4.5 4.5 0 0 1 0 9" /><path d="M11.5 7.5a.5 .5 0 1 0 1 0a.5 .5 0 1 0 -1 0" fill="currentColor" /><path d="M11.5 16.5a.5 .5 0 1 0 1 0a.5 .5 0 1 0 -1 0" fill="currentColor" /></svg>'
export const tabler_yoga =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-yoga" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M11 4a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" /><path d="M4 20h4l1.5 -3" /><path d="M17 20l-1 -5h-5l1 -7" /><path d="M4 10l4 -1l4 -1l4 1.5l4 1.5" /></svg>'
export const tabler_zeppelin_off =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zeppelin-off" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M15.773 15.783c-.723 .141 -1.486 .217 -2.273 .217c-2.13 0 -4.584 -.926 -7.364 -2.777l-2.136 1.777v-3.33a46.07 46.07 0 0 1 -2 -1.67a46.07 46.07 0 0 1 2 -1.67v-3.33l2.135 1.778c.13 -.087 .261 -.172 .39 -.256m2.564 -1.42c1.601 -.735 3.071 -1.102 4.411 -1.102c4.694 0 8.5 2.686 8.5 6c0 1.919 -1.276 3.627 -3.261 4.725" /><path d="M10 15.5v4.5h6v-4" /><path d="M3 3l18 18" /></svg>'
export const tabler_zeppelin =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zeppelin" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M13.5 4c4.694 0 8.5 2.686 8.5 6s-3.806 6 -8.5 6c-2.13 0 -4.584 -.926 -7.364 -2.777l-2.136 1.777v-3.33a46.07 46.07 0 0 1 -2 -1.67a46.07 46.07 0 0 1 2 -1.67v-3.33l2.135 1.778c2.78 -1.852 5.235 -2.778 7.365 -2.778" /><path d="M10 15.5v4.5h6v-4" /></svg>'
export const tabler_zero_config =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zero-config" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 12a8 8 0 1 0 16 0a8 8 0 1 0 -16 0" /><path d="M3 21l18 -18" /></svg>'
export const tabler_zip =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zip" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M16 16v-8h2a2 2 0 1 1 0 4h-2" /><path d="M12 8v8" /><path d="M4 8h4l-4 8h4" /></svg>'
export const tabler_zodiac_aquarius =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-aquarius" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10l3 -3l3 3l3 -3l3 3l3 -3l3 3" /><path d="M3 17l3 -3l3 3l3 -3l3 3l3 -3l3 3" /></svg>'
export const tabler_zodiac_aries =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-aries" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M12 5a5 5 0 1 0 -4 8" /><path d="M16 13a5 5 0 1 0 -4 -8" /><path d="M12 21l0 -16" /></svg>'
export const tabler_zodiac_cancer =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-cancer" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" /><path d="M15 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" /><path d="M3 12a10 6.5 0 0 1 14 -6.5" /><path d="M21 12a10 6.5 0 0 1 -14 6.5" /></svg>'
export const tabler_zodiac_capricorn =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-capricorn" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 4a3 3 0 0 1 3 3v9" /><path d="M7 7a3 3 0 0 1 6 0v11a3 3 0 0 1 -3 3" /><path d="M13 17a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" /></svg>'
export const tabler_zodiac_gemini =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-gemini" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 3a21 21 0 0 0 18 0" /><path d="M3 21a21 21 0 0 1 18 0" /><path d="M7 4.5l0 15" /><path d="M17 4.5l0 15" /></svg>'
export const tabler_zodiac_leo =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-leo" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M13 17a4 4 0 1 0 8 0" /><path d="M3 16a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" /><path d="M7 7a4 4 0 1 0 8 0a4 4 0 1 0 -8 0" /><path d="M7 7c0 3 2 5 2 9" /><path d="M15 7c0 4 -2 6 -2 10" /></svg>'
export const tabler_zodiac_libra =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-libra" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M5 20l14 0" /><path d="M5 17h5v-.3a7 7 0 1 1 4 0v.3h5" /></svg>'
export const tabler_zodiac_pisces =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-pisces" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M5 3a21 21 0 0 1 0 18" /><path d="M19 3a21 21 0 0 0 0 18" /><path d="M5 12l14 0" /></svg>'
export const tabler_zodiac_sagittarius =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-sagittarius" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 20l16 -16" /><path d="M13 4h7v7" /><path d="M6.5 12.5l5 5" /></svg>'
export const tabler_zodiac_scorpio =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-scorpio" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 4a2 2 0 0 1 2 2v9" /><path d="M5 6a2 2 0 0 1 4 0v9" /><path d="M9 6a2 2 0 0 1 4 0v10a3 3 0 0 0 3 3h5l-3 -3m0 6l3 -3" /></svg>'
export const tabler_zodiac_taurus =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-taurus" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M6 3a6 6 0 0 0 12 0" /><path d="M6 15a6 6 0 1 0 12 0a6 6 0 1 0 -12 0" /></svg>'
export const tabler_zodiac_virgo =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zodiac-virgo" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 4a2 2 0 0 1 2 2v9" /><path d="M5 6a2 2 0 0 1 4 0v9" /><path d="M9 6a2 2 0 0 1 4 0v10a7 5 0 0 0 7 5" /><path d="M12 21a7 5 0 0 0 7 -5v-2a3 3 0 0 0 -6 0" /></svg>'
export const tabler_zoom_cancel =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-cancel" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" /><path d="M8 8l4 4" /><path d="M12 8l-4 4" /><path d="M21 21l-6 -6" /></svg>'
export const tabler_zoom_check =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-check" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" /><path d="M21 21l-6 -6" /><path d="M7 10l2 2l4 -4" /></svg>'
export const tabler_zoom_code =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-code" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" /><path d="M21 21l-6 -6" /><path d="M8 8l-2 2l2 2" /><path d="M12 8l2 2l-2 2" /></svg>'
export const tabler_zoom_exclamation =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-exclamation" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" /><path d="M21 21l-6 -6" /><path d="M10 13v.01" /><path d="M10 7v3" /></svg>'
export const tabler_zoom_in_area =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-in-area" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M15 13v4" /><path d="M13 15h4" /><path d="M10 15a5 5 0 1 0 10 0a5 5 0 1 0 -10 0" /><path d="M22 22l-3 -3" /><path d="M6 18h-1a2 2 0 0 1 -2 -2v-1" /><path d="M3 11v-1" /><path d="M3 6v-1a2 2 0 0 1 2 -2h1" /><path d="M10 3h1" /><path d="M15 3h1a2 2 0 0 1 2 2v1" /></svg>'
export const tabler_zoom_in =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-in" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" /><path d="M7 10l6 0" /><path d="M10 7l0 6" /><path d="M21 21l-6 -6" /></svg>'
export const tabler_zoom_money =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-money" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" /><path d="M21 21l-6 -6" /><path d="M12 7h-2.5a1.5 1.5 0 0 0 0 3h1a1.5 1.5 0 0 1 0 3h-2.5" /><path d="M10 13v1m0 -8v1" /></svg>'
export const tabler_zoom_out_area =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-out-area" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M13 15h4" /><path d="M10 15a5 5 0 1 0 10 0a5 5 0 1 0 -10 0" /><path d="M22 22l-3 -3" /><path d="M6 18h-1a2 2 0 0 1 -2 -2v-1" /><path d="M3 11v-1" /><path d="M3 6v-1a2 2 0 0 1 2 -2h1" /><path d="M10 3h1" /><path d="M15 3h1a2 2 0 0 1 2 2v1" /></svg>'
export const tabler_zoom_out =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-out" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" /><path d="M7 10l6 0" /><path d="M21 21l-6 -6" /></svg>'
export const tabler_zoom_pan =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-pan" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M9 12a3 3 0 1 0 6 0a3 3 0 0 0 -6 0" /><path d="M17 17l-2.5 -2.5" /><path d="M10 4l2 -2l2 2" /><path d="M20 10l2 2l-2 2" /><path d="M4 10l-2 2l2 2" /><path d="M10 20l2 2l2 -2" /></svg>'
export const tabler_zoom_question =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-question" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" /><path d="M21 21l-6 -6" /><path d="M10 13l0 .01" /><path d="M10 10a1.5 1.5 0 1 0 -1.14 -2.474" /></svg>'
export const tabler_zoom_replace =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-replace" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M21 21l-6 -6" /><path d="M3.291 8a7 7 0 0 1 5.077 -4.806a7.021 7.021 0 0 1 8.242 4.403" /><path d="M17 4v4h-4" /><path d="M16.705 12a7 7 0 0 1 -5.074 4.798a7.021 7.021 0 0 1 -8.241 -4.403" /><path d="M3 16v-4h4" /></svg>'
export const tabler_zoom_reset =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-reset" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M21 21l-6 -6" /><path d="M3.268 12.043a7.017 7.017 0 0 0 6.634 4.957a7.012 7.012 0 0 0 7.043 -6.131a7 7 0 0 0 -5.314 -7.672a7.021 7.021 0 0 0 -8.241 4.403" /><path d="M3 4v4h4" /></svg>'
export const tabler_zoom_scan =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom-scan" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 8v-2a2 2 0 0 1 2 -2h2" /><path d="M4 16v2a2 2 0 0 0 2 2h2" /><path d="M16 4h2a2 2 0 0 1 2 2v2" /><path d="M16 20h2a2 2 0 0 0 2 -2v-2" /><path d="M8 11a3 3 0 1 0 6 0a3 3 0 0 0 -6 0" /><path d="M16 16l-2.5 -2.5" /></svg>'
export const tabler_zoom =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zoom" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" /><path d="M21 21l-6 -6" /></svg>'
export const tabler_zzz_off =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zzz-off" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 12h6l-6 8h6" /><path d="M14 4h6l-5.146 6.862m1.146 1.138h4" /><path d="M3 3l18 18" /></svg>'
export const tabler_zzz =
  '<svg aria-hidden="true" class="icon icon-tabler icons-tabler-outline icon-tabler-zzz" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 12h6l-6 8h6" /><path d="M14 4h6l-6 8h6" /></svg>'

export type TablerIconNameChunk5 =
  | 'tabler:xbox-x'
  | 'tabler:xbox-y'
  | 'tabler:xd'
  | 'tabler:xxx'
  | 'tabler:yin-yang'
  | 'tabler:yoga'
  | 'tabler:zeppelin-off'
  | 'tabler:zeppelin'
  | 'tabler:zero-config'
  | 'tabler:zip'
  | 'tabler:zodiac-aquarius'
  | 'tabler:zodiac-aries'
  | 'tabler:zodiac-cancer'
  | 'tabler:zodiac-capricorn'
  | 'tabler:zodiac-gemini'
  | 'tabler:zodiac-leo'
  | 'tabler:zodiac-libra'
  | 'tabler:zodiac-pisces'
  | 'tabler:zodiac-sagittarius'
  | 'tabler:zodiac-scorpio'
  | 'tabler:zodiac-taurus'
  | 'tabler:zodiac-virgo'
  | 'tabler:zoom-cancel'
  | 'tabler:zoom-check'
  | 'tabler:zoom-code'
  | 'tabler:zoom-exclamation'
  | 'tabler:zoom-in-area'
  | 'tabler:zoom-in'
  | 'tabler:zoom-money'
  | 'tabler:zoom-out-area'
  | 'tabler:zoom-out'
  | 'tabler:zoom-pan'
  | 'tabler:zoom-question'
  | 'tabler:zoom-replace'
  | 'tabler:zoom-reset'
  | 'tabler:zoom-scan'
  | 'tabler:zoom'
  | 'tabler:zzz-off'
  | 'tabler:zzz'
